### ISSUE TITLE
개인 개발 환경에서 지원 플랫폼을 실행해 본다. - 5월 23일

### ISSUE THREAD

**Issue by woowahan-pjs** [woowacourse/service-issues#101]
- 저장소: https://github.com/woowacourse/service-apply
- 4기에게 전하는 문서: https://boiling-magpie-93b.notion.site/4-e62e01b841d94f43ac2e96a5098c72a0

관련 이슈: #79

**Comment by woowahan-pjs** [comment]
### 팀

- 케이, 로마, 비녀
- 차리, 조조그린, 자스민
- 제로, 애쉬, 우디
- 페퍼, 파랑, 록바, 소피아

**Comment by SuyeonChoi** [comment]
## 로컬에서 이메일 인증 뚫고 회원가입 완수하기(초간단!)
<img width="496" alt="image" src="https://user-images.githubusercontent.com/28749734/169681690-13688c7c-7f38-4e1f-b932-f602f3a94ee3.png">
이메일을 입력하고 메일인증을 클릭하였지만 아무리 기다려도 인증 메일은 오지 않았다...🥲

### DB관련 애플리케이션을 사용하는 경우
1. 다음 정보를 입력하여 데이터베이스에 접속한다.
```
Host: 127.0.0.1
Username: root
Password: root
Port: 53306
```
<img width="1312" alt="image" src="https://user-images.githubusercontent.com/28749734/169681621-2691e90d-45ce-4d31-a03c-08da5d506886.png">

2. `apply` 데이터베이스를 선택한뒤, `authentication_code`테이블을 선택한다. 
<img width="930" alt="image" src="https://user-images.githubusercontent.com/28749734/169681799-72cfa9b1-cfb4-4ecc-b369-cd6cd479ae7a.png">

3. `code` 컬럼에 생성된 인증 코드를 입력한다.
<img width="487" alt="image" src="https://user-images.githubusercontent.com/28749734/169681861-c0ce9b1a-aecf-4733-8087-01b78bcc75cf.png">

4. 이메일 인증 완료! 회원가입을 이어서 진행 가능하다!
<img width="485" alt="image" src="https://user-images.githubusercontent.com/28749734/169681886-d28d3003-71ee-47a6-8d51-8a1c41545f86.png">

### 콘솔만 사용하는 경우
1. docker로 실행되고 있는 컨테이너 이름을 확인한다.
```
$ cd docker
$ docker ps
```
<img width="1188" alt="image" src="https://user-images.githubusercontent.com/28749734/169682133-eef5db9c-bd27-4e49-9d01-f2cb609960bc.png">

2. 컨테이너 NAME으로 DB에 접속한다.
```
$ docker exec -it apply-db bash 
root@f25090be44d0:/# mysql -uroot -proot
```
<img width="684" alt="image" src="https://user-images.githubusercontent.com/28749734/169682160-4e666369-ee11-453c-b885-e2abc78bce93.png">

3. SQL 쿼리로 `code` 컬럼을 확인한다.
```
mysql> use apply;
mysql> select * from authentication_code;
```



## 의문
이메일 인증 유효시간이 지나도 DB에 저장된 데이터는 제거되지 않는다. 누군가 악의적으로 이메일 데이터를 계속 추가하면 어떻게 될까?🤔
<img width="612" alt="image" src="https://user-images.githubusercontent.com/28749734/169681904-a55c3e0e-620d-4ac9-9204-4e43c967285f.png">

**Comment by cjlee38** [comment]
## 현상
- README.md 에 있는 quick start 가이드를 따라 실행하던 중, `./gradlew clean vaadinPrepareFrontend` 명령어가 실행되지 않음.
- node.js 를 다운로드하는데 실패
<img width="766" alt="image" src="https://user-images.githubusercontent.com/52564093/170880441-9712db11-f643-4e25-8d87-5a81f550e64f.png">

## 해결
- gradle JVM을 구동하는 JDK버전을 변경
  - (기존) Azul Zulu Community (11.0.13)
  - (변경) OpenJDK (15.0.2) (다른 버전도 가능할 것으로 추측)

## 원인
> (주의) 원인을 명확하게 밝혀내지 못한 이슈입니다. 추후에 발견할 시 수정하겠습니다.

단서 1. node.js 를 다운 받는 URI가 잘못됨.
- `https://nodejs.org/dist/v12.16.0/node-v12.16.0-darwin-arm64.tar.gz`
- 하지만 실제 해당 경로에 파일이 존재하지 않는 모습을 볼 수 있음.
<img width="725" alt="image" src="https://user-images.githubusercontent.com/52564093/170880013-c7bf81af-e5d1-4c69-8e9e-634e26973f2a.png">

단서 2. JDK 변경시 다운로드 요청을 보내는 URI가 변경됨
- 변경된 JDK로 task 실행시, WireShark로 확인해본 결과 nodejs.org에 해당하는 IP(104.20.22.46:443)로 향하는 패킷이 전송되지 않음을 확인. (filter : `ip.dst >= 104.20.0.0 && ip.dst <= 104.20.255.255`)
- 기존에 homebrew로 설치한 node(/opt/homebrew/opt/node@16/bin)와 변경JDK로 설치한 node(~/.vaadin/node) 삭제시 오류 재발생


**결론 - JDK 버전이 변경됨에 따라, node를 다운로드 받는 URI가 달라지는 것으로 추측**

**Comment by asebn1** [comment]
## 윈도우 이슈 : Delete `␍` prettier/prettier 해결 방법
![image](https://user-images.githubusercontent.com/57438644/170978305-31487c2d-f3b4-44d1-a83d-f31beb669c1d.png)


- `frontend` 패키지에 `.eslintrc.json` 을 추가한다.
![image](https://user-images.githubusercontent.com/57438644/170978213-39dab34c-c433-45ca-a346-df89e2c9ec30.png)

```
{
  "extends": ["react-app", "prettier"],
  "plugins": ["prettier"],
  "rules": {
    "prettier/prettier": ["error", { "endOfLine": "auto" }]
  }
}
```

해결완료!

**Comment by soyi47** [comment]
## 1. 관리자 페이지(8080)에 접속하면 로그인 폼이 나타나지 않는 문제
- 우아한테크코스 텍스트만 보이고, form 내부 요소들이 보이지 않는다.
![image](https://user-images.githubusercontent.com/71116429/170977633-b4a61721-4966-44c5-9bd2-8f664689d04e.png)

### 버전을 맞추어 해결
- Gradle JVM과 JDK 버전 변경
![image](https://user-images.githubusercontent.com/71116429/170977873-c91bc299-67d5-4aa7-9255-c0cf7f80f5b9.png)
  (11.0.15에서도 동작)
- npm version: 7.15.1
- node version: 16.3.0

## 2. Application.kt 실행 시 아래와 같은 에러 발생
![image](https://user-images.githubusercontent.com/71116429/170978222-73f9433d-dc79-47e3-a700-3ec6ee80fac1.png)

### 해결
- 에러 알림창의 `Shorten the command line and rerun` 눌렀더니 잘 실행된다.
