### ISSUE TITLE
지원 플랫폼에서 개선하고 싶은 점을 찾는다. - 5월 30일

### ISSUE THREAD

**Issue by woowahan-pjs** [woowacourse/service-issues#102]
- [ ] JUnit 5 -> Kotest로 마이그레이션한다.
- [ ] Kotlin DSL을 사용하여 인수 테스트 픽스처를 만든다.
- [ ] woowacourse/service-apply/issues/273
- [ ] 만료된 인증 코드를 제거하는 방법을 연구하고 구현한다.
- [ ] 자바스크립트를 타입스크립트로 마이그레이션한다.
- [ ] 지원 플랫폼 3.0 UI를 고려한다.
- [ ] 프론트엔드 라이브러리 버전을 올린다.
- [ ] 다른 플랫폼을 사용해 보고 벤치마킹할 부분을 정리한다.

관련 이슈: #76

**Comment by lokba** [comment]
@소피아랑 같이 진행했습니다.
아직 수정하고 싶은 부분이 있어, 현재로써는 노션 문서를 올리고 추후에 수정 후 코멘트에 올리겠습니다.🥵

[노션 링크](https://emerald-stove-ccb.notion.site/09bf6290dbdf475493d22348af98b58c)

**Comment by KangYunHo1221** [comment]
#### 지원 플랫폼에서 현재까지 수정했으면 좋겠는 기능 사항과, 추가로 진행했으면 좋을 사항입니다!!

#### 추가 기능
- 작성한 지원서 세부내용 조회 기능
- 중복지원 금지
- 로그인 창 하단에 회원가입 링크 제공
- page contents 가 없을떄와 loding시 spinner등을 이용한 상태 알림

##### 수정해야할 기능
- 키보드 탭키로 input창 이동시 달력이 없어지지 않음
- Authentication code의 fetch를 실패했을 시 무조건 '이미 존재하는 이메일' 을 alert하는 오류 수정
- React version 최신화

#### 추가 사항
- TS migration
- CSS module
- Storybook을 이용한 test 및 명세 제공

**Comment by greenblues1190** [comment]
## 개선사항
- TypeScript 마이그레이션
- 테스트 커버리지 확대

**Comment by hwangstar156** [comment]
## 개선 사항

- js -> ts 마이그레이션
- 커스텀 훅 및 로직들에 대한 단위테스트 추가
- 상태관리 라이브러리 변경
- form UI 변경
- suspense및 errorBoundary로 로딩, 에러 관리하기
- 성?능 최적?화
- css 라이브러리 변경
- css animation 추가
- react-query 같은 데이터 페칭 라이브러리 이용하기(5기 힘내라), 안되면 hook으로 라이브러리 직접 만들어서 쓰자!

**Comment by jojogreen91** [comment]
### 조조그린 & 케이 개선사항

- 패키지 분리(application 내부)
- 문서화(API Spec, 주석, notion ...)
- assignment 의 PR 주소 자동입력(회원 깃 계정을 기준으로)
- 관리자서버에서 부정행위자의 합격을 선택할 수 없도록 처리

**Comment by kbsat** [comment]
### 로마 & 제로 개선사항
[개선사항 찾아보기](https://kbsat.notion.site/17f575229aa343b789f98bab6cf29275)
- application 내에 패키지 분리 ( test에서도 마찬가지 )
- 토큰 개선?
    - accessToken은 탈취될 가능성이 있어서 만료시간을 짧게 가져간다고 배웠는데 현재 12시간으로 만료시간이 설정되어 보안상 좋지 않을 것으로 예상된다.
    - 따라서 refresh 토큰을 도입해보는 것은 어떨까?

**Comment by woowahan-pjs** [comment]
- 기능 요구 사항을 자동 채점한다.
- 관리 도구 UI/UX를 개선한다.
- 관리자는 페어로 평가할 수 있다.
- woowacourse/service-apply/issues/66

**Comment by dongho108** [comment]
## 애쉬 & 차리 개선사항

* 전반적인 패키지 재구성
* 테스트 커버리지 높이기
* 로컬에서 프론트, 백 서버 실행 자동화 (모두가 같은 환경에서 실행할 수 있도록)
* 로컬에서 실행시 기본적인 테스트 데이터를 자동으로 세팅할 수 있는 기능

**Comment by woowahan-pjs** [comment]
### 2.1.0 개발

- 프론트엔드 라이브러리 버전을 올린다.
- 지원 페이지 UI/UX를 개선한다.
   - 다른 플랫폼을 사용해 보고 벤치마킹할 부분을 정리한다.
- 코틀린과 스프링 부트 버전을 올린다.
- JUnit 5 -> Kotest로 마이그레이션한다.
- Kotlin DSL을 사용하여 인수 테스트 픽스처를 만든다.
- woowacourse/service-apply/issues/273

### 3.0.0 개발

- 자바스크립트를 타입스크립트로 마이그레이션한다.
- 기능 요구 사항을 자동 채점한다.
- 관리 도구 UI/UX를 개선한다.
- 관리자는 페어로 평가할 수 있다.
- woowacourse/service-apply/issues/66
- 만료된 인증 코드를 제거하는 방법을 연구하고 구현한다.
