### ISSUE TITLE
플래닝 포커를 소개한다. - 6월 2일

### ISSUE THREAD

**Issue by woowapark** [woowacourse/service-issues#103]
소개 문서 : [지원 플랫폼 근로 플래닝 시작하기.pdf](https://github.com/woowacourse/service-issues/files/8821830/default.pdf)

**Comment by woowahan-pjs** [comment]
- [포커, 어디까지 쳐봤니 – 서비스 개발에 플래닝 포커 도입 사례 (feat. 원격근무)](https://tech.kakao.com/2020/09/08/planning-poker)
- [데일리 미팅! 플래닝 포커! 회고!](https://techblog.woowahan.com/2548)
- [플래닝 포커를 이용한 프로젝트 일정 산정](https://bcho.tistory.com/1041)
