### ISSUE TITLE
지원 플랫폼 2.1.0 개발 이슈를 할당한다. - 6월 7일

### ISSUE THREAD

**Issue by woowahan-pjs** [woowacourse/service-issues#105]
- 프론트엔드 라이브러리 버전을 올린다. - @hwangstar156 @KangYunHo1221 
- 지원 페이지 UI/UX를 개선한다. 
   - 다른 플랫폼을 사용해 보고 벤치마킹할 부분을 정리한다. - @lokba @greenblues1190 @soyi47 
- 코틀린과 스프링 부트 버전을 올린다. - @woowahan-pjs 
- JUnit 5 -> Kotest로 마이그레이션한다. - @asebn1 @jojogreen91 @cjlee38 
- Kotlin DSL을 사용하여 인수 테스트 픽스처를 만든다. - @summerlunaa @dongho108 
- woowacourse/service-apply/issues/273 - @kbsat @SuyeonChoi @kth990303

**Comment by greenblues1190** [comment]
## 지원 페이지 UI/UX를 개선한다.
### 다른 플랫폼을 사용해 보고 벤치마킹할 부분을 정리한다. - @lokba @greenblues1190 @soyi47
[notion](https://www.notion.so/UI-UX-8e09b587612b4871ba3ad331e9d1d724)

**Comment by greenblues1190** [comment]
## 다른 플랫폼을 사용해 보고 벤치마킹할 부분을 정리한다. - @lokba @greenblues1190 @soyi47

[notion](https://subsequent-motorcycle-de8.notion.site/UI-UX-8e09b587612b4871ba3ad331e9d1d724)
