### ISSUE TITLE
conversation 타임스탬프가 겹치지 않도록 한다.

### ISSUE THREAD

**Issue by LTTTTTE** [woowacourse/service-issues#35]
https://github.com/woowacourse/archive/pull/4

![image](https://user-images.githubusercontent.com/7259103/82894087-fac9fa00-9f8c-11ea-8021-b99d90a862a3.png)

Slack API로 부터 숫자 16자리의 TimeStamp 를 받는다.
현재 코드는 TimeStamp를  LocalDateTime변환하고 데이터베이스에 저장하는 과정에서
숫자 13자리만을 LocalDateTime 으로 저장한다.

```
Timestamp(13자리).toLocalDateTime();
```

TimeStamp의 누락된 뒷3자리는 nanosecond로 보인다.

만약 특정 사용자가 장문의 글과 코드블록 여러개를 본문에 넣어서 전송할경우,
그 본문은 코드블록을 기준으로 두개의 글로 나뉘어져서 보내지게 된다.
결국 두 글은 다른 타임스탬프를 가지게 된다.

그런데 이 두 글의 타임스탬프 차이가 nanosecond 차이가 발생할 수 있다.

![image](https://user-images.githubusercontent.com/7259103/82895338-06b6bb80-9f8f-11ea-9586-6cc0fca247c7.png)

<hr>

![image](https://user-images.githubusercontent.com/7259103/82895361-146c4100-9f8f-11ea-8cea-68325f4f054f.png)

이런 경우가 발생할 경우, 데이터베이스에 동일한 값을 가진 LocalDateTime이 INSERT 될 수 있으며,
Conversation의 timestamp는 unique 필드이며 예외를 발생 시킨다.

**Comment by woowahanCU** [comment]
nanosecond 의 차이가 있었군요.
LocalDateTime으로 변환이 안되어서 잘랐던건데, 그 부분 로직이 변경되어야겠네요.

https://github.com/woowacourse/archive/commit/2bb932cc1bab341d2333a4f0690fbb1264f461e2

현재는 unique 설정을 제거하여 해결했는데요. 이 부분은 fix하여 다시 반영해야겠네요.

**Comment by LTTTTTE** [comment]
저희가 해봐도 될까요?

**Comment by woowahanCU** [comment]
그럼요 당연하요~ ㅎㅎ

**Comment by lowoon** [comment]
https://github.com/woowacourse/archive/pull/4
