### ISSUE TITLE
신규 근로 학생을 위한 OJT를 준비한다.

### ISSUE THREAD

**Issue by woowahan-pjs** [woowacourse/service-issues#44]
신규 근로 학생: 시카, 범블비, 히로

- [x] @woowacourse/service-worker 에 추가 - @woowahan-pjs 
- [x] 테코브러리 어드민 권한 부여 - @woowahan-pjs 
   - 신착 도서를 추가한다.
- [x] 아카이브 서비스 소개 - @toneyparky 
- [x] 아카이브 서비스에 대한 간단한 이슈를 추가한다. - @toneyparky 
   - 아카이브 서비스에 대한 간단한 기능을 개발한다.

**Comment by toneyparky** [comment]
`아카이브 서비스에 대한 간단한 이슈를 추가한다.`에 대하여

이슈화 하는 과정도 함께하면 좋을듯하여 노트로만 만들어두었습니다.
