### ISSUE TITLE
회의실 내껀데를 활성화한다.

### ISSUE THREAD

**Issue by woowahan-pjs** [woowacourse/service-issues#51]
연결된 구글 계정을 확인해 본다.

**Comment by ddaaac** [comment]
회의실 내껀데가 의존하고 있는 외부 라이브러리는 크게
Google Calendar API와 Slack API 두 가지 입니다.

아래 과정은 `회의실 내껀데`를 운영 환경과 별도의 환경에서 작동하게 하는 방법입니다.
(운영 환경과 다른 Slack workspace, Google 캘린더)

만약 외부 API의 변동사항이 있거나, 장애가 있는 경우 아래 가이드라인을 참고하면 좋을 것 같습니다.



# 서버

- 서버가 뜰 환경(ec2, local...)에 [서비스 코드](https://github.com/woowacourse/service-reservation) 를 clone합니다.

# Google Calendar API

- [google developer console](https://console.developers.google.com/apis) 접속 후 새 프로젝트를 생성합니다.

![1](https://user-images.githubusercontent.com/43440195/92210347-82e36800-eec9-11ea-8f7b-81a8984f104a.png)

- 새로 만든 프로젝트로 이동한 뒤, 구글 캘린더 api를 추가합니다.(마지막에 '사용' 버튼 클릭)

![Untitled](https://user-images.githubusercontent.com/43440195/92210826-68f65500-eeca-11ea-892d-de3ce42cd09c.png)

![Untitled](https://user-images.githubusercontent.com/43440195/92210905-8c210480-eeca-11ea-8e33-411dd836c5bc.png)

- 사용자 인증 정보를 생성합니다.

![1](https://user-images.githubusercontent.com/43440195/92211189-02be0200-eecb-11ea-81c4-ade6d979aed4.png)
![2](https://user-images.githubusercontent.com/43440195/92211194-03ef2f00-eecb-11ea-9e8a-bbac5c23e420.png)
![3](https://user-images.githubusercontent.com/43440195/92211198-05205c00-eecb-11ea-9b6c-53f647447032.png)

- 위 과정이 끝나면 json 파일이 다운로드 됩니다.
이를 아까 clone한 프로젝트의 `src/main/resources/credentials.json` 로 위치시킵니다.
파일명은 `credentials.json`으로 해주세요.

# Google Calendar

- [구글 캘린더](https://calendar.google.com/calendar/r) 접속 후, 캘린더를 생성합니다.
![4](https://user-images.githubusercontent.com/43440195/92212012-4feea380-eecc-11ea-9e98-174958c67170.png)

- 생성 후, 캘린더 설정으로 이동해서 시간대를 설정하고, 사용자를 추가합니다.
사용자를 추가할 때 이메일은 방금 api 콘솔에서 생성된 이메일을 사용하면 됩니다.

![5](https://user-images.githubusercontent.com/43440195/92212036-567d1b00-eecc-11ea-91ca-1a1b96d2f829.png)
![6](https://user-images.githubusercontent.com/43440195/92212038-57ae4800-eecc-11ea-80ae-d964304568d3.png)


- 추가한 사용자의 권한을 '변경 및 공유 관리'로 변경합니다.


![7](https://user-images.githubusercontent.com/43440195/92212045-5aa93880-eecc-11ea-910d-c3f9c31aac59.png)

- 코드를 clone한 서버의 환경변수로 캘린더 id를 등록합니다. 환경 변수 이름은 `CALENDAR_ID`로 합니다.
예시)`export CALENDAR_ID=o210si3uefpdd5cfnvalhjqtr4@group.calendar.google.com`
(환경변수 설정하는 방법은 [여기](https://memory.today/dev/23)를 참고)

![8](https://user-images.githubusercontent.com/43440195/92212064-60068300-eecc-11ea-8edd-5f4c3b98e00e.png)
![9](https://user-images.githubusercontent.com/43440195/92212069-609f1980-eecc-11ea-8be5-698f65507c21.png)

- 등록된 환경 변수는 아래 코드에서 사용됩니다.
![image](https://user-images.githubusercontent.com/43440195/92219810-05722480-eed6-11ea-8b3f-32d89593328d.png)


# Slack api

- [슬랙 api](https://api.slack.com/apps) 접속 후, 새 앱을 생성합니다.(테스트용 workspace가 없으면 새로 생성 후 진행 [링크](https://slack.com/create#email))
![10](https://user-images.githubusercontent.com/43440195/92212087-6432a080-eecc-11ea-91a5-14d5210ceb50.png)
![11](https://user-images.githubusercontent.com/43440195/92212116-6d237200-eecc-11ea-9ced-5d4437f447b9.png)



- 앱 생성 후, 첫 화면 아래에 Signing Secret 값이 있습니다. 이 값을 'show' 버튼을 눌러서 확인한 뒤, 앞과 마찬가지로 환경 변수 `SIGNING_SECRET` 으로 추가해줍니다.
그리고 임시로 `BOT_TOKEN` 이라는 환경변수도 아무 값이나 넣어서 저장해줍니다.

![12](https://user-images.githubusercontent.com/43440195/92212104-68f75480-eecc-11ea-9e6e-e43906838477.png)
![13](https://user-images.githubusercontent.com/43440195/92212108-6a288180-eecc-11ea-8c82-1ac1fbacc1f3.png)


- 여기까지 완료됐으면 스프링 서버를 돌릴 수 있습니다.
 `./gradlew clean bootRun` 명령어로 돌려보면 서버가 뜹니다. 슬랙 api의 인증을 받기 위해 서버를 띄워봅니다.
![14](https://user-images.githubusercontent.com/43440195/92212125-71e82600-eecc-11ea-9c00-b507839ad9df.png)


- 서버가 뜨면 'Event Subscription' 에서 이벤트를 enable 해주고,
`http://서버.주소/slack/action` 를 입력하면 인증이 완료됩니다(Verified가 뜨면 성공)

![15](https://user-images.githubusercontent.com/43440195/92212906-a4dee980-eecd-11ea-86b5-ac9cc9db37ff.png)


- 이어서 Bot User Event에 `app_mention` 을 추가 후 저장합니다.

![16](https://user-images.githubusercontent.com/43440195/92212910-a6a8ad00-eecd-11ea-9fc2-e20a8339b170.png)


- 'OAuth & Permissions' 탭으로 이동해서 권한에 `chat:write` 추가합니다.

![17](https://user-images.githubusercontent.com/43440195/92212920-ab6d6100-eecd-11ea-8960-afffc4e85a7f.png)


- 앱 설치

![18](https://user-images.githubusercontent.com/43440195/92212929-af00e800-eecd-11ea-8846-9407c9e9748e.png)


- 서버를 잠깐 끄고,
발급된 bot token을 복사한 값으로 아까 임시로 채워넣었던 환경변수 `BOT_TOKEN`를 수정합니다.


![19](https://user-images.githubusercontent.com/43440195/92212944-b4f6c900-eecd-11ea-969f-780f93f91a7e.png)
![20](https://user-images.githubusercontent.com/43440195/92212948-b627f600-eecd-11ea-9c5d-3772ee191fb3.png)


- 서버를 재시작합니다.
- 마지막으로 'Interactivity & Shortcuts' 탭에서 interaction할 주소를 입력합니다.
`http://서버.주소/slack/interaction`

![21](https://user-images.githubusercontent.com/43440195/92212955-b922e680-eecd-11ea-8e61-14e4c91ec6fc.png)


# Slack

- 앱을 채널에 추가합니다.

![22](https://user-images.githubusercontent.com/43440195/92212960-bcb66d80-eecd-11ea-828a-02e4ef59afdd.png)


![23](https://user-images.githubusercontent.com/43440195/92212965-bf18c780-eecd-11ea-9538-546b093b39c3.png)


- 회의실 내껀데가 동작하는 것을 확인합니다.

![24](https://user-images.githubusercontent.com/43440195/92212972-c344e500-eecd-11ea-95e9-b64383265925.png)
