### ISSUE TITLE
레벨2 미션 페이먼츠 모바일 앱 프로토타이핑을 요청합니다.

### ISSUE THREAD

**Issue by pocojang** [woowacourse/service-issues#52]
**제작이 필요한 기능 혹은 서비스 이름**: 프론트엔드 레벨2 Figma 프로토타이핑

**완료 희망일**: 2021년 4월 19일

**기간에 해당하는 레벨을 선택해 주세요.**

- [x] 레벨 2: 웹 프로그래밍 개발은 미숙하기 때문에 서비스 제작은 MVP가 존재해야 합니다.
- [ ] 레벨 3: 기획부터 개발까지 모든 것에 참여할 수 있습니다.
- [ ] 레벨 4: 제작보다 취업 준비를 우선합니다.

**제작에 필요한 도구와 프로그래밍 언어**:  피그마

**제작 범위를 선택해 주세요.**

- [x] 기획
- [x] 디자인
- [ ] 개발

**참고할 수 있는 기능, 서비스, 뼈대 코드 URL**: 

- [#2 피그마를 왜 써야 하는데?](https://brunch.co.kr/@ggk234/3)
- [스타트업 마케터가 피그마를 좋아하는 이유](https://medium.com/%EC%98%A4%EC%9D%BC%EB%82%98%EC%9A%B0-%ED%8C%80-%EB%B8%94%EB%A1%9C%EA%B7%B8/%EB%82%98%EB%8A%94-%ED%94%BC%EA%B7%B8%EB%A7%88-%EC%97%86%EC%9D%B4-%EB%AA%BB%EC%82%B4%EC%95%84-3b83d5be8541)
- [디자인 작업을 구글독스처럼 바꿔버린 피그마](http://www.ttimes.co.kr/view.html?no=2020010911387716045)
- ['피그마 Figma', 주목 받는 UI GUI 디자인 프로그램](https://www.wedesignx.com/knowledge/figma-ui-gui-design-program)

**제작이 필요한 기능 혹은 서비스에 대해 구체적으로 설명해 주세요.**:

- [요구사항 및 와이어 프레임](https://www.figma.com/file/yiNEKvD9Z3ESi7dZZX1J7M/%ED%8E%98%EC%9D%B4%EB%A8%BC%EC%B8%A0)
- 프론트엔드 미션
  - 시안을 보며 CSS를 직접 구현할 수 있는 환경을 만들 필요가 있습니다.
  - 기획 요구사항을 구체화하는게 중요한 포지션이다보니 기획적인 요구 사항도 함께 고민해야합니다.

**Comment by woowahanCU** [comment]
@devJang 
위의 요구사항만에는 디자인 시안에 대한 가이드가 없는데요.
1. 디자인 가이드에 제약은 없나요? (전적으로 제작근로 크루들에게 일임하는걸까요?)
2. 수업 혹은 미션을 통해 전달하려는 메시지가 어떤 형태의 디자인이든 영향을 받지는 않나요?
3. LMS에서 피그마를 사용할지, 이를 어떻게 활용할지에 대해서는 좀 더 논의가 필요하다고 생각해요.

**Comment by woowapark** [comment]
`레벨2에서는 미션 2개의 디자인 시안이 필요합니다` 
-> 요 부분 관련해서 미션 2개 자체의 요구사항을 함께 적어주시면 좋을 것 같습니다..!

**Comment by pocojang** [comment]
> @devJang
> 위의 요구사항만에는 디자인 시안에 대한 가이드가 없는데요.
> 
> 1. 디자인 가이드에 제약은 없나요? (전적으로 제작근로 크루들에게 일임하는걸까요?)
> 2. 수업 혹은 미션을 통해 전달하려는 메시지가 어떤 형태의 디자인이든 영향을 받지는 않나요?
> 3. LMS에서 피그마를 사용할지, 이를 어떻게 활용할지에 대해서는 좀 더 논의가 필요하다고 생각해요.

1. 없습니다!
이 부분은 전적으로 위임하는 것이 아닌 코스를 설계하는 코치들과 함께 소통해야할 부분이라고 생각하고 있습니다
2. 어차피 구현할 수 있는 실력이 충만한 상황은 아니라 최대한 시멘틱하게 하려고 하고 있습니다
3. 티켓만 미리 만들면 되지 않을까 생각합니다

**Comment by woowapark** [comment]
## 제작 근로용 figma 프로젝트
- https://www.figma.com/file/8O3tU0nlLsERQdFP6h2YXq/payments
- 혹시 위 링크로 접속해서 편집이 되지 않는다면 저에게 알려주세요~!
- 위에 포코가 요구사항&와이어프레임 올려주신 건 요 프로젝트로 복사해두었습니다.

**Comment by woowapark** [comment]
@woowahan-pjs @woowahanCU 
현재 이 `의뢰` 이슈에서 필요한 코멘트 달면서 진행하면 될까요? 
혹은 별도 작업 이슈 생성해서 진행하는 게 좋을까요?  
(기존에 관리하던 방식이 있을 지 해서 여쭤봅니다 :) )

**Comment by woowapark** [comment]
## 제작 완료 결과물 (read-only)
- https://www.figma.com/file/uDHr0HNizeHMNpCbxT69KV/payments?node-id=0%3A1

**Comment by woowapark** [comment]
요구사항에 맞춰 제작 완료하여 이슈 닫겠습니다 :)
