### ISSUE TITLE
레벨2 미션 장바구니 데스크탑 앱 프로토타이핑을 요청합니다.

### ISSUE THREAD

**Issue by pocojang** [woowacourse/service-issues#54]
**제작이 필요한 기능 혹은 서비스 이름**: 프론트엔드 레벨2 Figma 프로토타이핑

**완료 희망일**: 2021년 5월 3일

**기간에 해당하는 레벨을 선택해 주세요.**

- [x] 레벨 2: 웹 프로그래밍 개발은 미숙하기 때문에 서비스 제작은 MVP가 존재해야 합니다.
- [ ] 레벨 3: 기획부터 개발까지 모든 것에 참여할 수 있습니다.
- [ ] 레벨 4: 제작보다 취업 준비를 우선합니다.

**제작에 필요한 도구와 프로그래밍 언어**:  Figma

**제작 범위를 선택해 주세요.**

- [x] 기획
- [x] 디자인
- [ ] 개발

**참고할 수 있는 기능, 서비스, 뼈대 코드 URL**: 

- [배민 상회](https://mart.baemin.com)

**제작이 필요한 기능 혹은 서비스에 대해 구체적으로 설명해 주세요.**:

실제로 구현된 배민 상회 페이지를 클론하여 피그마로 옮깁니다. 
그 후 프론트엔드 크루들이 피그마 시안을 구현하며 미션을 수행합니다.

> 총 6페이지

- 상품 목록
- 상품 상세
- 장바구니
- 결제
- 주문 내역 목록
- 주문 내역 상세
- +@ 공통 GNB

> 요구사항 정리

![장바구니-미션-근로-요청 001](https://user-images.githubusercontent.com/23068523/115406680-5c8cf580-a22a-11eb-9949-bd2b641c1f36.jpeg)
![장바구니-미션-근로-요청 002](https://user-images.githubusercontent.com/23068523/115406694-60207c80-a22a-11eb-9c9f-9d11022e141f.jpeg)
![장바구니-미션-근로-요청 003](https://user-images.githubusercontent.com/23068523/115406697-6151a980-a22a-11eb-90c4-3a50a22f2d79.jpeg)
![장바구니-미션-근로-요청 004](https://user-images.githubusercontent.com/23068523/115406701-61ea4000-a22a-11eb-9298-7660ccca97f8.jpeg)
![장바구니-미션-근로-요청 005](https://user-images.githubusercontent.com/23068523/115406706-6282d680-a22a-11eb-892e-cd060c16070a.jpeg)
![장바구니-미션-근로-요청 006](https://user-images.githubusercontent.com/23068523/115406710-631b6d00-a22a-11eb-84eb-a6df3b110f82.jpeg)
![장바구니-미션-근로-요청 007](https://user-images.githubusercontent.com/23068523/115406717-644c9a00-a22a-11eb-8a82-b30ba050fcd9.jpeg)

- 기획적인 요구 사항도 함께 고민해야합니다.
- 클론하지만 상당 부분을 제거하며 피그마로 옮깁니다.
- 데스크탑 웹 앱을 지향합니다.
- 실제 프론트 크루들이 구현하며 심화로 할 수 있는 부분도 고려합니다.
- 백엔드 제작 근로 크루들이 참고할 수 있습니다.

**Comment by pocojang** [comment]
배민 상회 테스트 계정의 경우
[배민 사장님 광장](https://ceo.baemin.com)만 가입하시면 누구나 간단하게 배민 상회를 가입할 수 있습니다!
(저도 테스트 완료! / 사업자 번호같은 별도의 인증도 없습니다)

**Comment by woowapark** [comment]
@devJang 
작업이 완료되어 시안 공유드립니다 :)
https://www.figma.com/file/m3B8Ev4BsmuVco4jIclhYf/FE_Level2_Mission3_Shopping_Cart?node-id=0%3A1 

- 요구사항이 잘 반영되었는지
- 수정할 부분이 있을 지

한 번 확인 부탁드립니다. 먼저 보시고 짧게 미팅 잡아서 지난번처럼 확인하면 좋을 것 같습니다!
