### ISSUE TITLE
레벨2 미션 장바구니 API를 요청합니다. 

### ISSUE THREAD

**Issue by pocojang** [woowacourse/service-issues#56]
**제작이 필요한 기능 혹은 서비스 이름**: 프론트엔드 레벨2 미션 장바구니 API

**완료 희망일**: 2021년 5월 10일~11일

**기간에 해당하는 레벨을 선택해 주세요.**

- [x] 레벨 2: 웹 프로그래밍 개발은 미숙하기 때문에 서비스 제작은 MVP가 존재해야 합니다.
- [ ] 레벨 3: 기획부터 개발까지 모든 것에 참여할 수 있습니다.
- [ ] 레벨 4: 제작보다 취업 준비를 우선합니다.

**제작에 필요한 도구와 프로그래밍 언어**:  Java? JavaScript?  어떤게 좋을까요?

**제작 범위를 선택해 주세요.**

- [x] 기획
- [ ] 디자인
- [x] 개발

**참고할 수 있는 기능, 서비스, 뼈대 코드 URL**: 

- [배민 상회](https://mart.baemin.com)

**제작이 필요한 기능 혹은 서비스에 대해 구체적으로 설명해 주세요.**:

실제로 구현된 배민 상회의 일부 페이지를 구현합니다.

> 필요한 모든 API

- 장바구니 CRUD
- 주문내역 생성 및 조회

> 요구사항 정리

![장바구니-미션-근로-요청-be 001](https://user-images.githubusercontent.com/23068523/115488714-ef16ae80-a295-11eb-8fff-29dc228e95a0.jpeg)
![장바구니-미션-근로-요청-be 002](https://user-images.githubusercontent.com/23068523/115488724-f2aa3580-a295-11eb-8903-1ff6f9ed1d0d.jpeg)
![장바구니-미션-근로-요청-be 003](https://user-images.githubusercontent.com/23068523/115488727-f342cc00-a295-11eb-9988-9d543596307d.jpeg)
![장바구니-미션-근로-요청-be 004](https://user-images.githubusercontent.com/23068523/115488729-f3db6280-a295-11eb-83a4-f6b250486af0.jpeg)
![장바구니-미션-근로-요청-be 005](https://user-images.githubusercontent.com/23068523/115488730-f473f900-a295-11eb-8238-7cbb2d5d4a9c.jpeg)
![장바구니-미션-근로-요청-be 006](https://user-images.githubusercontent.com/23068523/115488731-f50c8f80-a295-11eb-8101-b664bc46e485.jpeg)
![장바구니-미션-근로-요청-be 007](https://user-images.githubusercontent.com/23068523/115488733-f50c8f80-a295-11eb-9790-b6b25579aaf4.jpeg)

- 기획적인 요구 사항도 함께 고민해야합니다.
- [프론트엔드 근로가 만드는 피그마](https://github.com/woowacourse/service-issues/issues/54)를 참고하면 더 도움될 수 있습니다.
- 웬만하면 로컬 API를 지향합니다
- JVM 환경이 필요할 경우 프론트엔드 크루들에게 가이드가 필요할 수 있습니다.

**Comment by woowahan-pjs** [comment]
- https://www.boorownie.com/docs/index.html
- https://github.com/gothinkster/realworld/tree/master/api

**Comment by woowahan-pjs** [comment]
# 요구 사항

### 상품

- 상품을 등록할 수 있다.
- 상품을 조회할 수 있다.
- 상품 목록을 조회할 수 있다.

### 장바구니

- 각 고객은 하나의 장바구니를 소유한다.
- 장바구니에 상품을 추가할 수 있다.
- 장바구니에 담긴 상품 목록을 조회할 수 있다.
- 장바구니에 상품을 삭제할 수 있다.

### 주문

- 각 고객은 여러 주문을 할 수 있다.
- 장바구니에 담긴 상품을 주문할 수 있다.
   - 주문된 상품은 장바구니에서 삭제된다.
- 주문 목록을 조회할 수 있다.

### 고객

- 고객의 이름은 GitHub username이며 대소문자를 구분하지 않는다.

**Comment by woowahan-pjs** [comment]
![shopping-cart](https://user-images.githubusercontent.com/48229284/116358685-e0ea0480-a838-11eb-8be4-09be8ec270b4.png)

```
@startuml
class Customer {
  id
  username
}

class Product {
  id
  name
  price
  imageUrl
}

class Cart {
  id
}

class Order {
  id
  amount
}

class OrderDetail {
  id
  quantity
}

Cart "1" --> "1" Customer : customer
Cart "1" --> "*" Product : products
Order "*" --> "1" Customer : customer
Order "1" --> "*" OrderDetail : details
OrderDetail "1" --> "1" Product : product
@enduml
```

**Comment by woowahan-pjs** [comment]
https://softwareengineering.stackexchange.com/questions/354675/what-to-rename-my-order-table

**Comment by pocojang** [comment]
완료 희망일을 변경했습니다!
장바구니 미션은 Step1 / Step2 나눠서 진행될 예정이며

- **Step1**
  - 프론트 크루들이 Mock Data 혹은 Mock API를 직접 만들어 사용하고 스키마까지 직접 설계하도록 유도
- **Step2**
  - 백엔드 근로 크루들의 노고가 담긴 API로 Endpoint와 스키마를 변경
  
위와 같이 진행될 예정이기때문에
Step2가 시작될 시기에 맞춰서 완료가 되어도 괜찮습니다!

> API에 대해서는 필히 보안 유지 부탁드립니다

**Comment by woowahan-pjs** [comment]
### 크루 인수 체크 리스트

- [x] API 문서(https://github.com/woowacourse/shopping-cart-api/blob/main/README.md)
- [x] API 문서에 맞게 구현한 프로젝트(https://github.com/woowacourse/shopping-cart-api)
- [x] CORS 활성화

### 코치 인수 체크 리스트

- [x] 인스턴스 생성
- [x] RDS 연결
- [x] 도메인 등록

**Comment by woowahanCU** [comment]
https://shopping-cart.techcourse.co.kr/
