### ISSUE TITLE
자바스크립트로 자판기 미션을 구현해 본다. - 5월 20일

### ISSUE THREAD

**Issue by woowahan-pjs** [woowacourse/service-issues#64]
현재 요구 사항대로 구현해 보고 느낀 점을 정리하는 시간이라고 생각해 주세요. 우선 CSS도 없는 상태에서 구현해 주시고 없이 시작하는 게 좋을지, 일정 부분 템플릿을 제공하는 게 좋을지 등도 고려해 봐주세요.

- 저장소: https://github.com/woowacourse/javascript-vendingmachine
- 요구 사항: #55

**Comment by zereight** [comment]
자바스크립트 자판기 미션 제작했습니다.  
\[PR\](woowacourse/javascript-vendingmachine#1)

**Comment by woowapark** [comment]
### 난이도
- 레이싱카 미션보다 쉬웠다
- 숫자 야구와 비슷하거나 조금 어려운 정도
  - 근데 레벨2 시점에 하니까 그래서 좀 더 쉽게 느껴졌는게 아닌가?
- 숫자 야구에서 다루는 지식으로 구현할 수 있지만, 고려해야 하는 인터랙션 등이 조금 더 많을 수 있다.
- 선택, 추가 등의 요구사항이 들어가면 프론트엔드쪽 난이도가 조금 올라가는 수준일 듯
