### ISSUE TITLE
자바로 자판기 미션을 구현해 본다. - 5월 20일

### ISSUE THREAD

**Issue by woowahan-pjs** [woowacourse/service-issues#65]
현재 요구 사항대로 구현해 보고 느낀 점을 정리하는 시간이라고 생각해 주세요.

- 저장소: https://github.com/woowacourse/java-vendingmachine
- 요구 사항: #55

**Comment by unluckyjung** [comment]
5월 18일 백엔드 미션 제작 파트 [회의록](https://github.com/woowacourse/java-vendingmachine/wiki/2021.05.18.-%EB%B0%B1%EC%97%94%EB%93%9C-%EB%AF%B8%EC%85%98-%EC%A0%9C%EC%9E%91-%ED%8C%8C%ED%8A%B8-%ED%9A%8C%EC%9D%98)
