### ISSUE TITLE
지원 플랫폼 > 지원자 페이지 스토리보드를 제작한다.

### ISSUE THREAD

**Issue by woowahan-pjs** [woowacourse/service-issues#66]
스토리보드 제작은 개선 작업에 들어가기 전에 기존에 구현된 지원 서비스를 파악하기 위한 작업으로 생각해 주세요.

- 요구사항 명세를 기준으로 현재 구현된 요구사항을 파악하고, 이후 마이그레이션 작업을 진행하게 된다면 어떤 기능들을 확인하며 옮겨야 할지 정리해 보는 작업입니다.
- figma로 옮기는 작업은 우선 진행해 보고, 다음 주간 회의 때 어느 정도 시간이 걸릴지 등을 확인해서 일정 맞춰 보면 좋을 것 같습니다.
- 레벨 2 동안은 기존 서비스를 문서화하는 차원에서 옮기는 거로 생각해주시고, 개선 제안이 있다면 이후에 별도 작업으로 논의해 주세요.

Vue -> React 마이그레이션

- 레벨 3 시작하면 @woowapark 와 같이 Vue 학습을 간단히 먼저 하고, 이후 마이그레이션 혹은 개선 작업을 진행하게 될 것 같아요.
- 오프라인으로도 얘기 나눴듯이 교육 과정을 고려했을 때 마이그레이션 하는 편이 이후에 효율이 더 높지 않을까 싶은데, 혹시 살펴보면서 다른 의견이 있다면 알려주시고요.

관련 이슈:

- https://github.com/woowacourse/service-apply/issues/6
- https://github.com/woowacourse/service-apply/issues/5
- https://github.com/woowacourse/service-apply/issues/4
- https://github.com/woowacourse/service-apply/issues/9
- https://github.com/woowacourse/service-apply/issues/10

**Comment by SunYoungKwon** [comment]
기존요구사항 파악 후 [정리한 내용](https://www.notion.so/66-626f18dacc0b4394b09defbac58cf89c)입니다.

**Comment by woowapark** [comment]
@SunYoungKwon 
썬 확인 중이고, 주간 회의에서도 같이 논의해보아야겠지만
- 개인 기록 공간보다는 프로젝트 공간에서 관리될 수 있으면 더 좋을 것 같아요! 
  - (아마도 https://github.com/woowacourse/service-apply ?)
- '기존요구사항 파악' 이 별도 작업으로 좀 더 확인해보아야 한다면 별도 이슈를 만들어서 관리해도 좋을 것 같네요 🤔 

주간회의에서 진행 확인하면서 다시 논의해보아요~!

**Comment by woowapark** [comment]
- 레벨 2에서는 지원자 페이지의 AS-IS를 figma로 옮기는 작업을 진행하였습니다.
https://www.figma.com/file/1gceuyT9aDojgnnUXWwurO/%EC%A7%80%EC%9B%90%EC%8B%9C%EC%8A%A4%ED%85%9C?node-id=0%3A1
- 관리자 페이지의 스토리보드 작업은 별도 이슈로 추가하여, 필요성과 작업 진행을 관리할 예정입니다.
