### ISSUE TITLE
자판기 미션에 대한 추가 기능 요구 사항을 도출한다. - 6월 2일

### ISSUE THREAD

**Issue by woowahan-pjs** [woowacourse/service-issues#70]

**Comment by unluckyjung** [comment]
[회의록 링크](https://github.com/woowacourse/service-issues/wiki/%5B2021-05-24-%EC%9B%94%5D-%EC%9E%90%ED%8C%90%EA%B8%B0-%EB%AF%B8%EC%85%98%EC%97%90-%EB%8C%80%ED%95%9C-%EC%B6%94%EA%B0%80-%EA%B8%B0%EB%8A%A5-%EC%9A%94%EA%B5%AC-%EC%82%AC%ED%95%AD-%EB%8F%84%EC%B6%9C-%ED%9A%8C%EC%9D%98)

**Comment by unluckyjung** [comment]
- step을 구분짓는 기준이 있어야할꺼 같다. 단순히 기능 구현을 통한 내용 추가라면 step을 나누는것이 무의미해 보인다. (공원)
- 현재 요구사항으로는 이 미션을 통해 얻는게 무엇이 있을지 잘 모르겠다. 미션을 통해서 기대하는것이 무엇인지 정의가 필요하다. (제이슨)
- 실제 미션처럼 구체적으로 요구사항을 만드는것은 힘들고, 일단 지금까지 도출한 요구사항을 기반으로 직접 구현해보고, 느낀점을 공유해야할 꺼 같다. (씨유)

**Comment by unluckyjung** [comment]
# 자동판매기 잔돈 계산 모듈 (프론트, 백 공통)

그저 반환되는 동전이 최소한이 되는 자판기 잔돈 계산 모듈을 구현해서 제공하면 충분하다.

- 최소 개수의 동전으로 잔돈을 돌려준다.
  예) 1000원 넣고 650원짜리 음료를 선택했다면, 잔돈은 100, 100, 100, 50원으로 반환한다.
- 지폐를 잔돈으로 반환하는 경우는 없다고 가정한다.

---

## 기능 요구 사항

- [ ] 잔돈 모듈에 동전을 넣으면 얼마가 들었는지 알 수 있다.
- [ ] 잔돈 모듈에 든 금액을 차감할 수 있다.
- [ ] VendingMachine을 ChangesModule로 변경한다.
- [ ] 동전은 500원, 100원, 50원, 10원이 있다.
- [ ] 없는 금액의 동전인 경우
- [ ] 최소 개수의 동전으로 잔돈을 돌려준다.
  - [ ] 10원이 남아 있다면 10원 동전 1개를 돌려준다.
  - [ ] 50원이 남아 있다면 50원 동전 1개를 돌려준다.
  - [ ] 1000원이 남아 있다면 500원 동전 2개를 돌려준다.
  - [ ] 20원이 남아 있다면 10원 동전 2개를 돌려준다.
  - [ ] 600원이 남아 있다면 500원 동전 1개와 100원 동전 1를 돌려준다.
  - [ ] 650원이 남아 있다면 500원 동전 1개와 100원 동전 1와 50원 동전 1개를 돌려준다.
  - [ ] 1원이 남아 있다면 동전을 돌려주지 않는다.
  - [ ] 659원이 남아 있다면 500원 동전 1개와 100원 동전 1와 50원 동전 1개를 돌려준다.
- [ ] 상품의 목록이 주어진다.
  - [ ] {콜라, 1000원}, {사이다, 1500원}, {쿨피스, 700원}
- [ ] 상품의 추가하거나 삭제할 수 있다. 
  - [ ] 상품 추가 : {밀키스, 2000원}
  - [ ] 상품 삭제 : {콜라}
- [ ] 구입에 성공하거나, 실패한경우 구매완료한 상품의 이름과 개수를 보여준다. {쿨피스 1, 사이다2}
  - [ ] 구입은 한번에 한개밖에 하지못한다.
- [ ] 반환 요청을 하는 경우 잔돈이 반환된다.

~~구입에 성공했을때, 남은 금액이 최소 구입 금액 미만인 경우 잔돈이 반환된다. (1690원을 보유하고 있고 콜라(1000)를 사고 난뒤, 남은 잔돈이 690원 인경우, 최소금액인 쿨피스 700원보다 남은 금액이 낮으므로 잔돈이 반환된다.)~~

## Step2
- [ ] 10원짜리는 무한으로 있고, 50원, 100원, 500원 수량이 존재한다(자판기 보유량)
  - [ ] 1000원이 있는데, 전체 인출을 시도할 경우
  - [ ] 500원 1개, 100원 2개 (자판기 보유량)
  - [ ] 500x1, 100x2, 10x30 (반환 동전)

---

- ChangesModule
- ChangesModule#withDraw(Money)
- Coin(500원, 100원, 50원, 10원)
- Changes(잔돈) // Changes(10).coins() = Coins(Coin.\_10_COIN)

**Comment by woowahan-pjs** [comment]
# 1단계 - 잔돈 계산 모듈

## 기능 요구 사항

그저 반환되는 동전이 최소한이 되는 자판기 잔돈 계산 모듈을 구현해서 제공하면 충분하다.

- 최소 개수의 동전으로 잔돈을 돌려준다. 예) 1000원 넣고 650원짜리 음료를 선택했다면, 잔돈은 100, 100, 100, 50원으로 반환한다.
- 지폐를 잔돈으로 반환하는 경우는 없다고 가정한다.

# 2단계 - 돈통

## 기능 요구 사항

- 입력한 금액으로 동전을 무작위로 생성한다.
- 잔돈을 돌려줄 때 현재 보유한 최소 개수의 동전으로 잔돈을 돌려준다.
- 사용자가 입력한 금액에 대한 잔돈을 반환할 수없는 경우 입력한 금액을 그대로 반환한다.

# 3단계 - 자판기

## 기능 요구 사항

- 상품명, 수량, 금액을 추가할 수 있다.
- 사용자가 입력한 금액으로 상품 구매할 수 있다.
- 잔돈이 상품 최소 금액보다 적은 경우 바로 잔돈을 돌려준다.

### 실행 결과

```
자판기가 보유하고 있는 금액을 입력해 주세요.
10000

상품명과 수량, 금액을 입력해 주세요.
[콜라,20,1500],[사이다,10,1000]

투입 금액을 입력해 주세요.
3000

투입 금액: 3000원
구매할 상품명을 입력해 주세요.
콜라

투입 금액: 1500원
구매할 상품명을 입력해 주세요.
사이다

잔돈
500원 - 1개
```
