### ISSUE TITLE
지원 플랫폼의 현재 요구 사항을 파악하고 설명한다. - 5월 26일

### ISSUE THREAD

**Issue by woowahan-pjs** [woowacourse/service-issues#72]

**Comment by SunYoungKwon** [comment]
- [지원플랫폼(베타)](https://dutfk5np0ke8a.cloudfront.net/recruits)
- [관리자페이지(베타)](http://serviceapply-env.eba-tpdmgi6s.ap-northeast-2.elasticbeanstalk.com/admin/login) - woowaguest 망에서만 접근 가능

[지원플랫폼_요구사항조사_0526.pdf](https://github.com/woowacourse/service-issues/files/6544728/_._0526.pdf)
