### ISSUE TITLE
자판기 미션에 대한 도출한 추가 기능 요구 사항을 구현해 본다. - 6월 2일

### ISSUE THREAD

**Issue by woowahan-pjs** [woowacourse/service-issues#75]
예상 결과물: 각자의 PR

**Comment by 2SOOY** [comment]
[FE - 자판기 미션 구현해보기(콜린)](https://github.com/woowacourse/javascript-vendingmachine/pull/2)
[FE - 자판기 미션 구현해보기(도비)](https://github.com/woowacourse/javascript-vendingmachine/pull/3)

**Comment by unluckyjung** [comment]
[BE - 포츈 step1](https://github.com/woowacourse/java-vendingmachine/pull/9)
[BE - 포츈 step1, 2](https://github.com/woowacourse/java-vendingmachine/pull/10)
[BE - 시드 step1, 2](https://github.com/woowacourse/java-vendingmachine/pull/11)
[BE - 조이 step1, 2](https://github.com/woowacourse/java-vendingmachine/pull/12)
