### ISSUE TITLE
지원 플랫폼의 새로운 요구 사항을 정리한다. - 6월 2일

### ISSUE THREAD

**Issue by woowahan-pjs** [woowacourse/service-issues#76]
예상 결과물: 

- #72 의 결과를 텍스트로 정리힌다.
- https://github.com/woowacourse/service-apply/issues 에 이미 등록된 이슈가 있으면 그것과 연결한다.
- 지원 화면을 React로 마이그레이션할 때 함께 해결할 수 있는 요구 사항을 구분한다.

**Comment by woowahan-pjs** [comment]
실제 지원해 보고 최종 합격까지 평가해 보면 어떨까요? 관리자 친화적인 UI/UX로 발전하면 좋겠어요.

- 서류 평가 -> 1차 프리코스 평가 -> 2차 프리코스 평가 -> 최종 코딩 테스트

**Comment by woowapark** [comment]
+) 마이그레이션 포함, 이후 진행할 작업을 어떻게 할 지에 대한 프로세스도 함께 논의해볼 예정입니다.

**Comment by woowapark** [comment]
### 이후 전반적인 순서(이자 우선순위)
- 1 지원자 페이지 Vue -> React 마이그레이션
  - 마이그레이션하면서 함께 고칠 버그/수정사항(아주 작은 수준) 구분해서 함께 수정
  - 이외 기능단위의 버그 수정, 제안 사항은 마이그레이션부터 마친 뒤에 추가 논의 
- 2 신규 기능 추가
- 3 관리자 페이지 현재 코틀린 UI Framework -> React 전환

**Comment by woowapark** [comment]
### 논의 안건 
@SunYoungKwon @seojihwan 내일 논의 안건으로 참고해주세요~
- 위 순서 중 1번에 대한 작업 프로세스, 계획
  - figma 스토리보드 필요성
  - 개발 우선순위 및 백엔드 개발 작업과 의존성 있는 부분 확인
  - 개발 프로세스 확인
  - Vue 학습 및 마이그레이션 작업 계획
- 지원 화면을 React로 마이그레이션할 때 함께 해결할 수 있는 요구 사항을 구분
  - 연결된 이슈에서 정리한 현재 요구사항 정리 자료 기반

**Comment by woowapark** [comment]
## 지원자 페이지 마이그레이션  
- 기능 수정은 큰 단위에서 필요할 것 같지는 않음
- 레벨2 마무리 시점까지
   - figma로 현재 AS-IS 스토리보드 만들기
   - (요거 기준으로 레벨 3부터 실제 마이그레이션 작업 진행)
- 레벨3
   - 시작하면서 Vue 학습 진행
   - figma 참고해서 마이그레이션 실제 작업 일정 추산 및 진행  

### 진행할 이슈
- https://github.com/woowacourse/service-issues/issues/72 에서 정리한 이슈 중 이미 잘 구현되어 있는 요구사항은 그대로 마이그레이션

#### 마이그레이션 진행하면서 자잘하게 함께 고치거나 개선할 이슈
- [지원자 등록시 전화번호의 형식을 자동으로 맞춰주는 방식 개선](https://github.com/woowacourse/service-apply/issues/239)
- [지원자 등록 시 생년월일 입력 방식 개선](https://github.com/woowacourse/service-apply/issues/240)
- [새로고침 후에도 토큰이 유지되도록 개선](https://github.com/woowacourse/service-apply/issues/241)
- [입력 영역 UI 크기 확장](https://github.com/woowacourse/service-apply/issues/245)

#### 마이그레이션 완료 이후에 다시 확인해볼 이슈
- 아래 이슈들에 대해서는 필요성과 작업 범위에 대해 다시 논의가 필요합니다. 
- [로그인이 아니라, 좀 더 간단히 지원자에 대한 인증만 하기 위한 기능(용어 변경 혹은 기능 자체의 개선)](https://github.com/woowacourse/service-apply/issues/229)
- [지원서 제출 완료 후 내 지원서 내용 확인하기 기능](https://github.com/woowacourse/service-apply/issues/238)
- [지원자 등록시 유효한 이메일인지 인증하는 기능 추가](https://github.com/woowacourse/service-apply/issues/242) 
- [메인 페이지 디자인 개선](https://github.com/woowacourse/service-apply/issues/244)

**Comment by SunYoungKwon** [comment]
- [figma로 현재 AS-IS 스토리보드 만들기](https://www.figma.com/file/1gceuyT9aDojgnnUXWwurO/%EC%A7%80%EC%9B%90%EC%8B%9C%EC%8A%A4%ED%85%9C?node-id=0%3A1)

**Comment by woowapark** [comment]
@seojihwan @SunYoungKwon 
주간회의 때 논의했던 대로, 
- 위에서 정리한 마이그레이션에서 함께 개선할 이슈에 대한 작업 프로세스
- 디자인 개선 작업을 하는 경우, 개선 방향 등에 대한 레퍼런스      

는 추가로 논의 시간 잡아서 저에게도 공유 부탁드려요~
요구사항 정리 작업은 완료된 것으로 보고 요 이슈는 닫겠습니다.

**Comment by seojihwan** [comment]
**지원사이트 개선 방향**
- line height 변경
- 지원 폼의 너비 변경
- 배경색 변경 및 shadow 추가
- key color 설정

참고 레퍼런스: 우아한형제들 채용공고, 카카오 채용공고
[지원 사이트 조사.pdf](https://github.com/woowacourse/service-issues/files/6692328/default.pdf)
