### ISSUE TITLE
nextstep 플랫폼의 수강 신청 기능 테스트를 요청합니다.

### ISSUE THREAD

**Issue by woowahan-pjs** [woowacourse/service-issues#81]
**제작이 필요한 기능 혹은 서비스 이름**: nextstep 플랫폼의 수강 신청 기능 테스트
(e.g. 4기 프리코스를 위한 새로운 미션, nextstep 플랫폼의 스토리보드 등)

**완료 희망일**: 2021년 6월 28일

**기간에 해당하는 레벨을 선택해 주세요.**

- [ ] 레벨 2: 웹 프로그래밍 개발은 미숙하기 때문에 서비스 제작은 MVP가 존재해야 합니다.
- [x] 레벨 3: 기획부터 개발까지 모든 것에 참여할 수 있습니다.
- [ ] 레벨 4: 제작보다 취업 준비를 우선합니다.

**제작에 필요한 도구와 프로그래밍 언어**: http://techcourse.betabaemin.in
(e.g. 피그마, 자바스크립트, 코틀린, 스프링 프레임워크, 리액트 등)

**제작 범위를 선택해 주세요.**

- [ ] 기획
- [ ] 디자인
- [ ] 개발
- [ ] 교보재
- [x] 테스트

**참고할 수 있는 기능, 서비스, 뼈대 코드 URL**: 
(e.g. https://github.com/woowacourse/service-archive)

**제작이 필요한 기능 혹은 서비스에 대해 구체적으로 설명해 주세요.**:

관리자, 강사, 수강생 및 수강 대기자 역할을 적절하게 나눠 아래의 케이스에 대해 테스트합니다.
강의 타입 중 '무료 강의/자동 승인', '유료 강의/자동 승인', '유료 강의/개별 승인'에 대한 테스트가 이루어져야 합니다.
유료 강의는 테스트 종료 후 한꺼번에 환불하겠습니다.

- [ ] 수강 승인된 수강생 수가 정원보다 많을 수 없다
- [ ] 수강 승인된 수강생 수보다 정원을 줄일 수 없다
- [ ] 모집 상태를 변경할 수 있다
- [ ] 수강 후보자 수가 정원보다 많으면 수강 신청할 수 없다
- [ ] 이미 수강 신청한 수강생은 수강 신청할 수 없다
- [ ] 모집 상태가 모집 중이 아니라면 수강 신청할 수 없다
- [ ] 자동 승인 상태에 따라 수강 신청시 수강 승인 여부를 결정한다
- [ ] 수강 승인할 수 있다
- [ ] 수강 승인된 수강생 수가 정원보다 많으면 수강 승인할 수 없다
- [ ] 수강 승인 취소할 수 있다
- [ ] 수강생을 교체할 수 있다
- [ ] 이미 수강 신청한 수강생으로 수강생을 교체할 수 없다
- [ ] 수강 대기자를 수강생으로 교체할 수 있다
- [ ] 수강 대기 신청을 할 수 있다
- [ ] 수강 대기 번호를 알 수 있다
- [ ] 모집 상태가 모집 중이 아니라면 수강 대기 신청할 수 없다
- [ ] 수강 대기자를 승인할 수 있다
- [ ] 승인 받은 수강 대기자는 수강 신청할 수 있다
- [ ] 승인된 수강생 수가 정원을 넘기면 승인 받은 수강 대기자도 수강 신청할 수 없다
- [ ] 승인 받지 않은 수강 대기자는 수강 신청할 수 없다
- [ ] 수강 취소할 수 있다
- [ ] 수강 대기를 취소할 수 있다
- [ ] 초대 코드를 생성할 수 있다
- [ ] 초대 코드를 파기할 수 있다
- [ ] 모집 상태가 모집 중이 아니더라도 초대 코드를 통해 수강 신청이 가능하다
- [ ] 이미 수강 신청한 수강생은 초대 코드를 통해 수강 신청할 수 없다
- [ ] 초대 코드가 유효하지 않으면 수강 신청할 수 없다

### 수강 신청 버튼 클릭 시 표시되는 등록 상태

| 한글명 | 영문명 | 설명 |
| --- | --- | --- |
| 수강 대기 신청 | waiting | 모집하지 않을 때 손님, 사용자에게 표시되는 상태 |
| 수강 신청 | not enroll | 모집 중일 때 손님, 사용자에게 표시되는 상태 |
| 승인 대기 | enroll approving | 수강 승인 취소된 수강생에게 표시되는 상태 |
| 수강 중 | enroll approved | 수강 승인된 수강생, 강의 읽기 권한이 있는 사용자에게 표시되는 상태 |

**Comment by woowahan-pjs** [comment]
- TG 1: 콜린, 조이, 썬, 로키, 배럴, 아마찌, 코기
- TG 2: 도비, 시드, 포츈, 브랜, 마갸, 아론

**Comment by knae11** [comment]
# 수강생 
수강 승인된 수강생 수가 정원보다 많을 수 없다 -> 수강생
# 강사나 관리자
 수강 승인된 수강생 수보다 정원을 줄일 수 없다 -> 강사나 관리자
 모집 상태를 변경할 수 있다 -> 강사나 관리자
# 수강생
 수강 후보자 수가 정원보다 많으면 수강 신청할 수 없다 -> 수강생
 이미 수강 신청한 수강생은 수강 신청할 수 없다 -> 수강생
 모집 상태가 모집 중이 아니라면 수강 신청할 수 없다 -> 수강생
# 강사나 관리자
 자동 승인 상태에 따라 수강 신청시 수강 승인 여부를 결정한다 -> 강사나 관리자
 수강 승인할 수 있다 -> 강사나 관리자
 수강 승인된 수강생 수가 정원보다 많으면 수강 승인할 수 없다 -> 강사 관리자
 수강 승인 취소할 수 있다 -> 강사나 관리자
 수강생을 교체할 수 있다 -> 강사나 관리자
 이미 수강 신청한 수강생으로 수강생을 교체할 수 없다
 수강 대기자를 수강생으로 교체할 수 있다
# 수강생
 수강 대기 신청을 할 수 있다 -> 수강생
 수강 대기 번호를 알 수 있다 -> 수강생
 모집 상태가 모집 중이 아니라면 수강 대기 신청할 수 없다 
# 강사나 관리자
 수강 대기자를 승인할 수 있다
# 수강생 -> 강사 -> 수강생
 승인 받은 수강 대기자는 수강 신청할 수 있다
 승인된 수강생 수가 정원을 넘기면 승인 받은 수강 대기자도 수강 신청할 수 없다
# 수강생
 승인 받지 않은 수강 대기자는 수강 신청할 수 없다
 수강 취소할 수 있다
 수강 대기를 취소할 수 있다
# 강사나 관리자
 초대 코드를 생성할 수 있다
 초대 코드를 파기할 수 있다
# 강사 -> 수강생
 모집 상태가 모집 중이 아니더라도 초대 코드를 통해 수강 신청이 가능하다
 이미 수강 신청한 수강생은 초대 코드를 통해 수강 신청할 수 없다
 초대 코드가 유효하지 않으면 수강 신청할 수 없다

**Comment by knae11** [comment]
# 테스트 결과
테스트 완료하였습니다.
- 무료, 유료-자동, 유로-수동 상황에 대해 테스트 진행하였습니다. 
- https://www.notion.so/QA-16f19d2630544ff7b3ba275cca057a26

**Comment by woowahan-pjs** [comment]
### 버그

- 2개의 수강 신청 페이지를 띄워 두고 이미 수강 신청한 수강생도 수강 대기 신청할 수 있다.

### 개선 사항

- 2개의 수강 신청 페이지를 띄워 두고 정원을 넘기지 않은 상태에서 이미 수강 신청한 수강생이 한 번 더 수강 신청하는 경우 JSON이 노출된다.
   - `{"success":false,"message":"이미 수강 신청하였습니다.","body":""}`
- 2개의 수강 신청 페이지를 띄워 두고 무료 강의일 때 정원이 다 차면 결제 페이지로 넘어간다.
- 무료 강의/자동 승인, 유료 강의/개별 승인일 때 초대 링크 클릭 시 정원이 다 차면 결제 페이지로 넘어간다.

**Comment by ecsimsw** [comment]
버그 수정 확인하고, 다시 테스트 마쳤습니다. 

버그 : '2개의 수강 신청 페이지를 띄워 두고 이미 수강 신청한 수강생도 수강 대기 신청할 수 있다.'
