### ISSUE TITLE
웹 백엔드 미션 유틸리티 라이브러리를 기획한다. - 7월 21일

### ISSUE THREAD

**Issue by woowahan-pjs** [woowacourse/service-issues#83]

**Comment by Joyykim** [comment]
## 7/4 기획회의
- 제이슨: 로또를 생성하는 로직이 각자 다르니 테스트하기 어려웠다
    - 중복되지 않는 N개의 수 리스트를 반환(시작-끝 범위 지정)
- Collections.shuffle()
    - 인풋, 아웃풋이 있는 셔플 메서드
- Scanner
    - 안닫히는 스캐너.
- Random.nextInt()
    - RandomUtils 시작, 끝 범위 지정
- LocalDateTime
    - now()

### TODO

1. Scanner 안닫히게하는 법
- 라이브러리 구현
- 우리가 만든 라이브러리로 자판기 미션(제이슨 요구사항) 진행해보기~
- 크루들한테 QA 시키기

### 이번주 목표

1. 각자 하나씩 맡아서 유틸 클래스 만들기
2. 만든 유틸 클래스로 미션 진행
    1. 진행 중 추가적으로 필요한 유틸 클래스 확인, 요구사항 수정/추가

**Comment by Joyykim** [comment]
# 7/7 주간 회의
## 직접 만든 라이브러리 활용하여 미션 진행

- goal
    - 라이브러리의 효용성 확인
    - 추가로 필요한 라이브러리 있을지 확인
    - 개선 사항 확인
- 각 자 클래스 하나씩 잡고 구현, 미션 진행
- 7/11(일) 오후 17시에 미팅

### 라이브러리의 효용성 확인

- 기능이 필요한 도메인 구현
    - 예) 레이싱카에서 주사위 굴리는 부분, 로또 티켓 생성하는 부분 등

**Comment by hsik0225** [comment]
# 7/11 기획 회의
- 특정 월, 일 등을 추가한 날짜를 반환하는 API를 제공해줘야 할까?
아니다. 랜덤, 날짜와 같이 예상하지 못하는 값들을 테스트 하기 위해서 우리가 라이브러리를 제공해주는 것.
다른 메소드들은 로직이 일정하므로 우리가 제공안한 API를 사용해도 똑같이 동작한다.

- 테스트 하기 어려운 부분은 라이브러리로 제공하고, 테스트 하기 쉬운 부분에서 지원자들이 도메인 설계에 좀 더 고민할 수 있게 유도하는것이 어떨까?

## 예시

- `intsSet()` 의 기능
> N부터 M사이의 K개의 랜덤한 중복되지 않은 숫자들을 반환한다.

- 적용할 수 있는 미션
  - **야구게임** 미션 (1~9 사이의 4개의 중복되지 않는 숫자 목록 제공)
  - **로또** 미션 (1~45 사이의 6개의 중복되지 않는 숫자 목록 제공)

지원자에게 중복 제거에 대한 고민을 줄어들게 한다.  
그러나 이부분을 묶어서 제공해야 mocking 하기에 용이하게 되어, 테스트하기가 편리해진다.

---

# 이번주 TODO
1. 각자 작성한 라이브러리 클래스들을 하나로 합치기
2. 작성한 util 라이브러리를 사용을 강제하며 크루들에게 미션 수행 요청 
  2.1 피드백받고, 수정해야 할 부분을 생각해보기

예시 소감평
- 예전에 고민을 많이 했어야 했던 부분이었는데, 고민할 부분이 많이 줄어들었다.
- 메소드 이름이 이해가 안갔다.

3. 중앙 저장소에 올릴지, 코드로 그냥 적어둘지 생각해보기

**Comment by unluckyjung** [comment]
- 일단 야구게임의 핵심 요소 중 하나인 랜덤 숫자 배정이 직접 구현하면 참가자 대부분 오류를 범하는 것으로 알고 있습니다. (프리코스 당시 다른 교육생 코드를 많이 열어봤습니다.) 이러한 부분을 제공해준다는 점이 기능 구현에만 집중 할 수 있다는 장점을 받았습니다.

- 또한 첫 주차 미션에서 Collection 사용법이 미숙한데, shuffle 을 제공해주는 부분도 인상적이었습니다. 직접 Collection 을 사용하려면 관련된 수십개의 메서드가 함께 노출되어 입문 단계에서 상당한 스트레스를 가져올 수 있지만, 미션에 딱 필요한 메서드만 제공하므로써 집중도를 높일 수 있다고 생각합니다. 

- 다만 아쉬운 부분은 intsSet 메서드 네이밍입니다. ints(범위내 숫자 픽) + Set(해당 메서드내에서 사용하는 자료구조)라는 점에서 정말 있는 그대로의 네이밍이기는 하나 1주차 미션을 접하는 입장에서는 좀 더 이해하기 쉬운 네이밍을 해도 좋다고 생각합니다. (pickRandomBaseballNumbers 이런식)

- nextInt 메서드 네이밍이 아쉽다. 프리코스 때도 nextInt 메서드 내부 동작을 살펴보고서 랜덤 숫자 발급 메서드임을 깨달았다.

- Input/Output View 관련 클래스나 뼈대 메서드를 유틸로 미리 제공해주는건 어떨까 싶다. 이번에 구현하면서도 [네이밍, static 하게 만들지, 인스턴스로 만들지] 고민이 됐다.

- Application 쪽에 final Scanner scanner = new Scanner(System.in); 제공해주는 이유를 주석으로 남겼으면 좋겠다.

- '랜덤 값을 어떻게 뽑아낼까' 라는 고민 없이 구현에만 집중할 수 있었다.

**Comment by Joyykim** [comment]
- intsSet 메서드의 네이밍이 메서드를 잘 설명하지 못하고 있는 것 같습니다.
- shuffle, DateUtils.now 는 자바의 기본Api와 거의 다른 점이 없는데 사용해야하는 이유를 잘 모르겠습니다.
- nextInt 는 음수도 반환 가능했으면 좋겠습니다.

**Comment by hsik0225** [comment]
- 메서드 네이밍 다 괜찮은 것 같다. 직관적이라서 바로 이해 가능했다.
- intsSet 메서드가 해주는 게 많아서 프리코스 참가자들이 미션을 쉽게 구현할 수 있게 된 것 같다. 이것이 의도한 바인지는 잘 모르겠다.
- Set만 반환하도록 한 것이 이해가 잘 가지 않았다. List를 사용할 때가 더 많은데 List를 반환하도록 해줬으면 좋겠다.

**Comment by Joyykim** [comment]
# 7/17 회의
피드백을 반영해 라이브러리 기능을 수정, 추가했습니다.
[현재까지 완성, 배포된 라이브러리 repository](https://github.com/Joyykim/wooteco-utils)
JitPack을 사용해 라이브러리 배포 완료했고 [라이브러리 배포 과정](https://github.com/Joyykim/TIL/blob/master/deploy/jitpack%EC%9C%BC%EB%A1%9C%20%EB%9D%BC%EC%9D%B4%EB%B8%8C%EB%9F%AC%EB%A6%AC%20%EB%B0%B0%ED%8F%AC%ED%95%98%EA%B8%B0.md)도 정리했습니다.
## 다음주 TODO
Scanner 이슈 처리: 크루들의 코드에 Scanner를 생성하지 않아도 되도록
