### ISSUE TITLE
웹 프론트엔드 미션 프로그래밍 요구 사항을 기획한다. - 7월 7일

### ISSUE THREAD

**Issue by woowahan-pjs** [woowacourse/service-issues#84]
### 미션 제작 파트에서 하는 일
- 미션 제작
- 만든 미션에 대한 채점을 자동화할 수 있는 방법, 조금 더 효율적으로 채점할 수 있는 방법에 대한 리서치

#### 지원 플랫폼 개발 파트와의 연결
- 지원 플랫폼에서 PR에 대해 테스트 커맨드 실행 -> 결과 확인
- 미션 제작 파트에서는 지원 플랫폼에서 실행할 `테스트 커맨드`를 어떻게 만들면 될 지 확인해서 제공
  - 어떤 툴을 쓸 지 ex. cypress
  - 어떻게 테스트를 통과한 것으로 판단할 수 있을 지

### 리서치 목표 
미션 종류에 관계 없이, 범용적으로 프론트엔드 구현 사항을 확인할 수 있는 방법을 연구
- 특정 id, selector 등을 넣지 않아도 구현 사항을 확인할 수 있을 지 확인
- 라이브러리 개발 필요성 확인
  - 내장 라이브러리를 대체시키는 게 아니라, 채점을 쉽게 할 수 있도록 하기 위해 지원자들이 내장 라이브러리 대신 지정해서 사용하도록 제공할 라이브러리 개발
  - ex. Random 라이브러리 
    - Random의 범위를 한 자리 수로만 제한하는 별도 라이브러리를 만들어 해당 라이브러리를 사용해서 
  - ex2. Date 관련 라이브러리 
    - 포맷 등을 정해진 포맷으로만 리턴하도록 강제

### 리서치 후
- 구현 시 특정한 가이드에 따라야만 한다면(id, selector 등 지정) 
- 별도 라이브러리 개발이 크게 의미가 없을 것 같다면     

추가 리서치&개발을 진행하지 않고 미션을 만드는 일에 집중

**Comment by zereight** [comment]
`테스트 가능한 미션`을 제작하는 것이 목적이고, 범용적으로 사용할 수 있는 라이브러리를 개발할 수 있으면 더 좋다.

⇒ 프로그래머스 과제를 참고한 결과,

각 UI들을 class로 틀을 잡아놓고, js상에서 구현만 하도록 설계한다.

class이름과 메서드가 강제되어있으므로 내부 로직테스트 가능하고,
멤버 변수로 DOM요소를 들고 있기 때문에 DOM 테스트도 가능하다.

변경해도 되는 메서드와, 응시자가 구현해야할 메서드를 구별하여 미션을 작성.

⇒ 응시자가 구현한 메서드를 기반으로 테스트를 진행함

jest, cypress 테스트 도구 고려 

장점 : `testable` 하다. (각각의 UI에 대해서, class내에 비즈니스 로직 메서드와 DOM 요소들이 모두 있고, class 마다 공통적인 메서드들이 있기 때문에 범용적인 테스트코드를 작성할 수도 있다)

단점 : 

- 구조 자체를 강제한다.
- class 지식이 필요하다.
- 지원자들의 코드간의 다양성이 줄어듦
- DOM 요소, 메서드 이름이 강제된다.
- 실수로라도, 수정하지 말아야할 코드를 수정한 응시자는 노력과 코드의 퀄리티에 상관없이 낮은 점수를 받게 된다.
- 1개의 미션에 대해서 프리코스 기간이 1주일 정도인데, 기간을 맞추기 위해서 출제자가 제작해야할 보일러플레이트 코드 양이 많아진다.

결론 :

- 다음주 ACTION plan
    - 보일러 플레이트 코드 작성 (핵심 기능 - 흐름 파악을 위함) + 테스트 코드 작성
        - 금액 충전
        - 상품 구매
        - 상품 구매 출력
- `미션의 자유도` vs `테스트의 용이함` 둘간의 trade off문제라고 생각함



<img width="932" alt="스크린샷 2021-07-07 오후 2 55 42" src="https://user-images.githubusercontent.com/42544600/124707171-68d44500-df33-11eb-9401-6274920ad1a0.png">

cf)
랜덤 및 날짜 모듈 관련 ⇒ 백엔드 측에서 구현한 방식에 대한 설명을 들어야할 것 같습니다.

**Comment by zereight** [comment]
jest/cypress 둘다 TC가 몇개 통과했는지 알 수 있는데, UI까지 하려면 cypress 해야할듯하다!

**Comment by 2SOOY** [comment]
## Cypress CLI TEST (21.07.11)

### TEST 진행
```sh
# 1. local 서버 띄우기
npx http-server -p 5500

# 2. 특정 파일에 대해 cli로 cypress 실행
npx cypress run --spec "cypress/integration/vending/**/*"
```

### TEST 결과
```
# 테스트 일부

 Running:  vending/purchase.spec.js                                                        (4 of 4)


  상품 구매
    ✓ 충전 금액이 1000원인 상태에서 1000원 이상의 상품을 구매할 경우 alert (1495ms)
    ✓ 충전 금액이 5000원인 상태에서 5000원 이하의 상품을 구매할 경우 잔액이 차감된다. (638ms)
    ✓ 충전 금액이 5000원인 상태에서 상품을 구매할 경우 구매한 상품이 표시된다. (657ms)


  3 passing (4s)


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        3                                                                                │
  │ Passing:      3                                                                                │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        true                                                                             │
  │ Duration:     4 seconds                                                                        │
  │ Spec Ran:     vending/purchase.spec.js                                                         │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘

```

```
# 테스트 종합
 (Run Finished)


       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  vending/change.spec.js                   00:06        4        4        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  vending/charge.spec.js                   00:04        4        4        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  vending/productManage.spec.js            00:07        5        4        1        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  vending/purchase.spec.js                 00:04        3        3        -        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✖  1 of 4 failed (25%)                      00:22       16       15        1        -        -  
```

**Comment by 2SOOY** [comment]
(+ 추가로 실패 case에 대한 screenshot 정보도 저장됨)

![image](https://user-images.githubusercontent.com/46412689/125186946-11521400-e268-11eb-9ab6-ddaf79f52627.png)

**Comment by zereight** [comment]
- 저번주에 토의한 UI를 class로 나누어서 뼈대코드를 제공하는 방법이 테스팅 가능할 것으로 판단. 
다음주 안으로 자판기 미션 상품 구매페이지에 대한 제작완료 목표
    - 이 방법은 jest로 테스트코드를 작성하는 것이 적합하다.
    - 응시자에게 class 뼈대코드 + 간단한 테스트 코드 제공하여 의도한 구조로 작성하도록 유도
        - 실제 채점때에는 히든 테스트 코드로 채점
        - 출제자: 도비, 응시자: 콜린 으로 테스트 해볼예정
