### ISSUE TITLE
지원 플랫폼 2.0.0 테스트를 요청합니다.

### ISSUE THREAD

**Issue by woowahan-pjs** [woowacourse/service-issues#96]
**제작이 필요한 기능 혹은 서비스 이름**: 지원 플랫폼 2.0.0 테스트
(e.g. 4기 프리코스를 위한 새로운 미션, nextstep 플랫폼의 스토리보드 등)

**완료 희망일**: 2021년 10월 15일

**기간에 해당하는 레벨을 선택해 주세요.**

- [ ] 레벨 2: 웹 프로그래밍 개발은 미숙하기 때문에 서비스 제작은 MVP가 존재해야 합니다.
- [ ] 레벨 3: 기획부터 개발까지 모든 것에 참여할 수 있습니다.
- [x] 레벨 4: 제작보다 취업 준비를 우선합니다.

**제작에 필요한 도구와 프로그래밍 언어**: [Bug report](https://github.com/woowacourse/service-apply/issues/new?assignees=&labels=%EB%B2%84%EA%B7%B8&template=bug_report.md&title=), [2.0.0 QA 프로젝트](https://github.com/woowacourse/service-apply/projects/6)
(e.g. 피그마, 자바스크립트, 코틀린, 스프링 프레임워크, 리액트 등)

**제작 범위를 선택해 주세요.**

- [ ] 기획
- [ ] 디자인
- [ ] 개발
- [ ] 교보재
- [x] 테스트

**참고할 수 있는 기능, 서비스, 뼈대 코드 URL**: 

- [1.0.0 QA 프로젝트](https://github.com/woowacourse/service-apply/projects/3)
- [지원사이트 2.0.0 UI 디자인](https://www.figma.com/file/1gceuyT9aDojgnnUXWwurO/%EC%A7%80%EC%9B%90%EC%8B%9C%EC%8A%A4%ED%85%9C?node-id=207%3A2)
- [지원사이트 2.0.0 프로토타입](https://www.figma.com/proto/1gceuyT9aDojgnnUXWwurO/%EC%A7%80%EC%9B%90%EC%8B%9C%EC%8A%A4%ED%85%9C?node-id=207%3A298&scaling=min-zoom&page-id=207%3A2&starting-point-node-id=207%3A298&show-proto-sidebar=1)

(e.g. https://github.com/woowacourse/service-archive)

**제작이 필요한 기능 혹은 서비스에 대해 구체적으로 설명해 주세요.**:

관리자와 사용자, 지원자 역할을 적절하게 나눠 테스트합니다.
테스트 중 발생한 문제는 [Bug report](https://github.com/woowacourse/service-apply/issues/new?assignees=&labels=%EB%B2%84%EA%B7%B8&template=bug_report.md&title=) 형식으로 기록하여 [2.0.0 QA 프로젝트](https://github.com/woowacourse/service-apply/projects/6)에 등록합니다.
기타 불편하거나 필요한 부분을 이슈로 기록하여 [2.0.0 QA 프로젝트](https://github.com/woowacourse/service-apply/projects/6)에 등록합니다.

**Comment by NewWisdom** [comment]
# 지원 화면

## Applicant(User) - 회원

### **회원가입 & 이메일 인증**

- [ ]  올바른 정보를 기입할 시 회원가입에 성공한다.
- [ ]  각각 다른 스레드에서 동시에 같은 이메일로 회원가입을 하면 회원가입 요청은 하나만 성공한다.
- [ ]  이미 가입된 이메일인 경우 회원가입에 실패한다.
- [ ]  인증되지 않은 이메일로 회원가입 시도시 실패한다.
- [ ]  마지막에 인증 확인이 된 이메일로만 가입할 수 있다.
- [ ]  회원가입 시 자동으로 로그인 상태가 된다.
- [ ]  (보류) 현재는 이메일 인증을 마치고 가입 버튼을 누르기 전,다른 창에서 같은 메일로 인증 코드를 다시 보낸 후 원래 창으로 돌아와 가입 할 시 예외

**이메일 인증**

- [ ]  이메일 인증 코드 요청시 작성한 이메일로 인증코드를 발급한다.
- [ ]  가입되어 있는 이메일로 인증 코드 발급 요청 시 발급 실패한다.
- [ ]  이메일 인증시 인증코드 발급 10분이 지나면 해당 인증 코드가 만료되어 인증할 수 없다.

**로그인 / 정보관리** 

- [ ]  올바른 지원자 로그인 요청시 로그인에 성공한다.
- [ ]  잘못된 지원자 로그인 요청시 로그인에 실패한다.
- [ ]  올바른 비밀번호 초기화 요청에 성공시 새로운 비밀번호를 이메일로 발송한다.
- [ ]  비밀번호 변경시 기존 비밀번호와 일치해야 변경에 성공한다.
- [ ]  비밀번호 변경시 기존 비밀번호와 일치하지 않으면 변경에 실패한다.
- [ ]  개인 정보 변경에서 전화번호를 변경할 수 있다.

## ApplicationForm - 지원서 작성

**임시저장**

- [ ]  임시저장 후 이어서 작성할 수 있다

**제출**

- [ ]  제출 후에는 수정할 수 없다.
- [ ]  같은 기수의 모집에 2번 이상 제출할 수 없다.
- [ ]  같은 기수 내의 한 모집에 지원 후 다른 모집의 지원서를 임시저장할 수 있다.
- [ ]  관리자가 설정한 모집 항목의 순서대로 질문들이 표시된다.
- [ ]  제출하기 버튼 활성화 상태에서, 관리자가 모집 상태를 불가능으로 변경하면  제출할 수 없다.
    - [ ]  기간 내 모집이지만 모집 불가능 상태일 경우 제출할 수 없다.
    - [ ]  기간이 지난 모집일 경우 제출할 수 없다.
- [ ]  제출하기 버튼 활성화 상태에서, 관리자가 모집 상태를 가능으로 변경하면 제출할 수 있다.
- [ ]  지원서 화면에서 모집 기간이 지났을 때 지원서를 제출할 수 없다.

## Recruitment - 모집

- [ ]  관리자 페이지에서 비공개된 모집은 조회할 수 없다.
- [ ]  모집 종료된 모집에는 지원할 수 없다.
- [ ]  모집 가능한 모집에는 지원할 수 있다.
- [ ]  전체, 모집 예정, 모집중, 모집 종료 탭에 모집 상태대로 분류된 모집들을 조회할 수 있다.
- [ ]  지원하기 버튼 활성화 상태에서, 관리자가 모집 상태를 불가능으로 변경하면  지원할 수 없다.
    - [ ]  기간 내 모집이지만 모집 불가능 상태일 경우 지원할 수 없다.
    - [ ]  기간이 지난 모집일 경우 지원할 수 없다.
- [ ]  지원하기 버튼 활성화 상태에서, 관리자가 모집 상태를 가능으로 변경하면 지원할 수 있다.

**Comment by NewWisdom** [comment]
# 지원 화면

## Applicant(User) - 회원

### **회원가입 & 이메일 인증**

- [ ]  올바른 정보를 기입할 시 회원가입에 성공한다.
- [ ]  각각 다른 스레드에서 동시에 같은 이메일로 회원가입을 하면 회원가입 요청은 하나만 성공한다.
- [ ]  이미 가입된 이메일인 경우 회원가입에 실패한다.
- [ ]  인증되지 않은 이메일로 회원가입 시도시 실패한다.
- [ ]  마지막에 인증 확인이 된 이메일로만 가입할 수 있다.
- [ ]  회원가입 시 자동으로 로그인 상태가 된다.
- [ ]  (보류) 현재는 이메일 인증을 마치고 가입 버튼을 누르기 전,다른 창에서 같은 메일로 인증 코드를 다시 보낸 후 원래 창으로 돌아와 가입 할 시 예외

**이메일 인증**

- [ ]  이메일 인증 코드 요청시 작성한 이메일로 인증코드를 발급한다.
- [ ]  가입되어 있는 이메일로 인증 코드 발급 요청 시 발급 실패한다.
- [ ]  이메일 인증시 인증코드 발급 10분이 지나면 해당 인증 코드가 만료되어 인증할 수 없다.

**로그인 / 정보관리** 

- [ ]  올바른 지원자 로그인 요청시 로그인에 성공한다.
- [ ]  잘못된 지원자 로그인 요청시 로그인에 실패한다.
- [ ]  올바른 비밀번호 초기화 요청에 성공시 새로운 비밀번호를 이메일로 발송한다.
- [ ]  비밀번호 변경시 기존 비밀번호와 일치해야 변경에 성공한다.
- [ ]  비밀번호 변경시 기존 비밀번호와 일치하지 않으면 변경에 실패한다.
- [ ]  개인 정보 변경에서 전화번호를 변경할 수 있다.

## ApplicationForm - 지원서 작성

**임시저장**

- [ ]  임시저장 후 이어서 작성할 수 있다

**제출**

- [ ]  제출 후에는 수정할 수 없다.
- [ ]  같은 기수의 모집에 2번 이상 제출할 수 없다.
- [ ]  같은 기수 내의 한 모집에 지원 후 다른 모집의 지원서를 임시저장할 수 있다.
- [ ]  관리자가 설정한 모집 항목의 순서대로 질문들이 표시된다.
- [ ]  제출하기 버튼 활성화 상태에서, 관리자가 모집 상태를 불가능으로 변경하면  제출할 수 없다.
    - [ ]  기간 내 모집이지만 모집 불가능 상태일 경우 제출할 수 없다.
    - [ ]  기간이 지난 모집일 경우 제출할 수 없다.
- [ ]  제출하기 버튼 활성화 상태에서, 관리자가 모집 상태를 가능으로 변경하면 제출할 수 있다.
- [ ]  지원서 화면에서 모집 기간이 지났을 때 지원서를 제출할 수 없다.

## Recruitment - 모집

- [ ]  관리자 페이지에서 비공개된 모집은 조회할 수 없다.
- [ ]  모집 종료된 모집에는 지원할 수 없다.
- [ ]  모집 가능한 모집에는 지원할 수 있다.
- [ ]  전체, 모집 예정, 모집중, 모집 종료 탭에 모집 상태대로 분류된 모집들을 조회할 수 있다.
- [ ]  지원하기 버튼 활성화 상태에서, 관리자가 모집 상태를 불가능으로 변경하면  지원할 수 없다.
    - [ ]  기간 내 모집이지만 모집 불가능 상태일 경우 지원할 수 없다.
    - [ ]  기간이 지난 모집일 경우 지원할 수 없다.
- [ ]  지원하기 버튼 활성화 상태에서, 관리자가 모집 상태를 가능으로 변경하면 지원할 수 있다.

**Comment by NewWisdom** [comment]
## 대기중인 기능들

### 메일 발송

### Mission

### Assignment

**Comment by NewWisdom** [comment]
# 관리 화면

### Recruitment - 모집 관리

- [ ]  전체 모집 정보를 조회할 수 있다.
- [ ]  모집과 모집항목을 함께 생성할 수 있다.
- [ ]  모집항목 없이 모집을 생성할 수 있다.
- [ ]  모집을 삭제할 수 있다.(지원 여부와 관계없이)
- [ ]  모집 가능 상태의 모집은 삭제할 수 없다.

### Cheater - 부정 행위자

- [ ]  모든 부정행위자 이메일을 조회할 수 있다.
- [ ]  부정행위자 조회시 부정행위자의 정보가 파기된 경우 `(이름 없음)`으로 표기된다.
- [ ]  부정행위자를 추가할 수 있다.
- [ ]  이미 등록된 이메일의 부정행위자를 추가할 수 없다.
- [ ]  부정행위자를 삭제할 수 있다.
- [ ]  이름이나 이메일로 지원자를 검색해 부정행위자를 추가할 수 있다.

### Evaluation - 평가 관리

- [ ]  평가를 추가할 수 있다.
- [ ]  특정 평가를 조회할 수 있다.
- [ ]  평가와 평가항목을 함께 생성할 수 있다.
- [ ]  평가항목 없이 평가를 생성할 수 있다.
- [ ]  모집 없이 평가를 생성할 수 없다.
- [ ]  모든 (상세한) 평가를 조회할 수 있다.
- [ ]  평가를 삭제할 수 있다.
- [ ]  이전 평가로 등록되어 있는 평가도 삭제 할 수 있다.

> **관리자가 실수하지 않는다는 가정하에 묻어두는 예외 상황들**
> 
- 평가 항목 순서가 중복 가능함
- 평가 항목 순서에 1부터 시작하지 않아도 됨
- 평가 항목 이름도 중복이 가능함
- 이전 평가 중복도 가능함 → 평가 대상자 불러오기 시 치명적일 수 있음
- 평가 항목의 최대 점수가 0점도 가능함

### EvaluationTarget(평가 대상자) - 선발 과정

- [ ]  불러오기 버튼으로 평가대상자를 업데이트 할 수 있다.
    - 부정 행위자로 등록된 평가 대상자는 불러오기시 불합격 상태가 된다.
    - 이전 평가에서 합격 상태인 평가 대상자들만 불러와진다.
    - 이전 평가가 없을 시 전체 평가 대상자를 불러온다.
- [ ]  탭을 클릭해서 해당 평가의 평가 대상자들을 조회할 수 있다.
- [ ]  평가지 다운로드 버튼으로 평가지를 다운로드 받을 수 있다
- [ ]  평가지를 업로드해 평가를 업데이트할 수 있다.
    - [ ]  FAIL, PASS, PENDING, WAITING 이외의 평가상태를 적는 경우 평가 결과가 업로드되지 않는다.
    - [ ]  평가 항목의 점수란에 숫자가 아니거나 최대 점수보다 높은 점수를 입력시 평가 결과가 업로드되지 않는다.
- [ ]  검색창을 통해 평가대상자를 검색할 수 있다
- [ ]  평가결과 다운로드로 평가결과 파일을 다운로드 받을 수 있다

**전체 지원자 탭**

- [ ]  전체 지원자를 조회할 수 있다.
- [ ]  `평가 결과 다운로드` 버튼을 누르면 지원자 정보 excel을 다운로드할 수 있다.

**평가 탭**

> 관리자 사용시 전제 사항 or 절대 실수하지 말아야 할 점
> 
- 평가 완료된 이전  평가는 평가 대상자 불러오기를 누르지 않는다.
- 프리코스 내에서는 부정 행위자가 발생하지 않는다.
- 평가지 업로드 시 평가지의 컬럼명이나 지원자의 정보는 건드리지 않는다.

**Comment by NewWisdom** [comment]
## 대기중인 기능들

### 메일 발송

### Mission

### Assignment

**Comment by knae11** [comment]
# 관리화면

## Mission(과제)
- [ ]  특정 모집의 모든 과제를 조회할 수 있다.
- [ ]  해당 평가에 이미 등록된 과제가 있는 경우 예외를 던진다.
- [ ]  과제를 추가할 수 있다.
- [ ]  과제를 삭제할 수 있다.
- [ ]  제출 가능한 상태의 과제를 삭제하면 예외가 발생한다.

## Term(기수)
- [ ]  기수 정보를 변경할 수 있다.
- [ ]  단독모집의 경우 수정할 수 없다.

## Assignment(과제 제출물)
- [ ]  과제 제출 기간이 아니면 과제를 생성할 수 없다.
- [ ]  관리자가 평가페이지에서 평가불러오기를 했을 때, 지원자 상태가 "대기" 중이었다. 상태가 "대기중"인 지원자가 과제를 제출하고, 관리자가 평가페이지에서 평가 불러오기를 다시 하면 상태가 "합격"으로 변경되어 있다. ("대기중"인 경우 과제를 제출하기만 하면 "합격"상태가 된다.)
- [ ]  제출 불가능한 과제의 과제물을 수정할 수 없다.
- [ ]  과제 제출 기간이 아니면 과제물을 수정할 수 없다.

## Mail
- [ ]  메일 발송 시 제목, 본문 없이 메일을 보낼 수 없다.
- [ ]  보낸사람 항목에 메일 발신자 계정이 "EMAIL"(문자그대로) 이 아니어야 한다.
- [ ]  받는 사람이 한 명도 없을 경우, 수신 확인용 계정에만 발송한다.
- [ ]  메일 발송 시, 수신 확인용 계정이 메일을 받는다.
- [ ]  50명 이상을 대상으로 메일을 발송 시, 50명 단위로 잘라서 메일을 보낸다.
- [ ]  메일 수신 시 숨김 참조로 수신하여 다른 수신자를 확인 할 수 없다.
- [ ]  개별 불러오기 기능(이름 또는 이메일로 검색가능)으로 수신자를 불러 올 수 있다.
- [ ]  그룹 불러오기 기능으로 모집, 평가, 평가 상태를 기반으로 수신자를 추가할 수 있어야 한다.
- [ ]  수신자가 중복 될 경우 리스트에 추가되지 않는다.
- [ ]  파일을 첨부해서 발송할 수 있다.
- [ ]  첨부된 파일을 X버튼을 눌러 삭제할 경우 해당 파일은 발송되지 않아야 한다.
- [ ]  메일 발송 시, 메일 관리 화면에 메일 제목, 보낸 시간 받은 사람 수가 표시되어야 한다.
- [ ]  메일 발송 시, 본문에 html 태그를 넣을 경우 태그로 인식된다. (`<a href="~~"/>`)
- [ ]  자세히 보기 버튼을 누를 경우 (첨부파일이 제외된)메일 발송 정보가 남아야 한다.

**Comment by MyaGya** [comment]
# 안내 사항

- 예외케이스가 추가로 발견될 경우 추가해주기 → 슬랙 채팅방에 공유해서 다른 팀이 알 수 있도록 해주시면 감사하겠습니다.
- PC를 기준으로 Chrome, Safari, Firefox 테스트 케이스 확인
- 모바일은 Chrome 과 Safari, Firefox 지원이 가능해야 합니다. 지원자 입장에서 모바일로 지원이 가능해야 합니다.
- UI가 깨지거나 에러메세지가 이상할 경우 스크린샷을 반드시 첨부해 주세요
- 버그 리포트 작성 시 재현 방법을 최대한 상세하게(주어진 상황, 환경, 재현 방식 등)

# 순서

## User (회원) - 🙋🏻‍♂️

### **회원가입 & 이메일 인증**

- [x]  올바른 정보를 기입할 시 회원가입에 성공한다.
- [x]  각각 다른 스레드에서 동시에 같은 이메일로 회원가입을 하면 회원가입 요청은 하나만 성공한다.
- [x]  이미 가입된 이메일인 경우 회원가입에 실패한다.
- [x]  인증되지 않은 이메일로 회원가입 시도시 실패한다.
- [x]  마지막에 인증 확인이 된 이메일로만 가입할 수 있다.
- [x]  회원가입 시 자동으로 로그인 상태가 된다.
- [x]  회원가입시 인증받은 인증코드와 다른 인증코드를 넘길시 회원가입에 실패한다.

**이메일 인증**

- [x]  이메일 인증 코드 요청시 작성한 이메일로 인증코드를 발급한다.
- [x]  가입되어 있는 이메일로 인증 코드 발급 요청 시 발급 실패한다.
- [ ]  이메일 인증시 인증코드 발급 10분이 지나면 해당 인증 코드가 만료되어 인증할 수 없다.
- [ ]  이메일 인증 후 입력된 이메일을 변경하면 인증이 취소된다.
    - [ ]  재 인증 시 제한시간(10분)이 초기화된다.

**로그인 / 정보관리**

- [x]  올바른 지원자 로그인 요청시 로그인에 성공한다.
- [x]  잘못된 지원자 로그인 요청시 로그인에 실패한다.
- [x]  올바른 비밀번호 초기화 요청에 성공시 새로운 비밀번호를 이메일로 발송한다.
- [ ]  비밀번호 변경시 기존 비밀번호와 일치해야 변경에 성공한다.
- [ ]  비밀번호 변경시 기존 비밀번호와 일치하지 않으면 변경에 실패한다.
- [x]  개인 정보 변경에서 전화번호를 변경할 수 있다.

## Term(기수) (모집생성), 모집수정에 버튼으로 확인가능 - 🛠️

- [ ]  기수를 생성할 수 있다.
- [ ]  기수 정보를 변경할 수 있다.
- [ ]  단독모집의 경우 수정할 수 없다.
- [ ]  기수 이름이 중복될 수 없다.

## Recruitment(모집 관리) - 🛠️

- [ ]  전체 모집 정보를 조회할 수 있다.
- [ ]  모집과 모집항목을 함께 생성할 수 있다.
- [ ]  모집항목 없이 모집을 생성할 수 있다.
- [ ]  모집을 삭제할 수 있다.(지원 여부와 관계없이)
- [ ]  모집 가능 상태의 모집은 삭제할 수 없다.

## Recruitment(모집) -  🙋🏻‍♂️

- [ ]  관리자 페이지에서 비공개된 모집은 조회할 수 없다.
- [x]  지원자는 모집 종료된 모집에는 지원할 수 없다.
- [x]  지원자는 모집 가능한 모집에는 지원할 수 있다.
- [x]  전체, 모집 예정, 모집중, 모집 종료 탭에 모집 상태대로 분류된 모집들을 조회할 수 있다.
- [x]  지원하기 버튼 활성화 상태에서, 관리자가 모집 상태를 불가능으로 변경하면 지원자는 지원할 수 없다.
    - [x]  지원자는 기간 내 모집이지만 모집 불가능 상태일 경우 지원할 수 없다.
    - [x]  지원잔기간이 지난 모집일 경우 지원할 수 없다.
- [x]  지원하기 버튼 활성화 상태에서, 관리자가 모집 상태를 가능으로 변경하면 지원할 수 있다.

## ApplicationForm(지원서 작성) - 🙋🏻‍♂️

**임시저장**

- [x]  임시저장 후 이어서 작성할 수 있다

**제출**

- [x]  제출 후에는 수정할 수 없다.
- [x]  제출 후에는 제출한 지원서 내용을 확인할 수 없다.
- [x]  같은 기수의 모집에 2번 이상 제출할 수 없다.
- [x]  같은 기수 내의 한 모집에 지원 후 다른 모집의 지원서를 임시저장할 수 있다.
- [x]  관리자가 설정한 모집 항목의 순서대로 질문들이 표시된다.
- [x]  제출하기 버튼 활성화 상태에서, 관리자가 모집 상태를 불가능으로 변경하면 제출할 수 없다.
    - [x]  기간 내 모집이지만 모집 불가능 상태일 경우 제출할 수 없다.
    - [x]  기간이 지난 모집일 경우 제출할 수 없다.
- [x]  제출하기 버튼 활성화 상태에서, 관리자가 모집 상태를 가능으로 변경하면 제출할 수 있다.
- [ ]  지원서 화면에서 모집 기간이 지났을 때 지원서를 제출할 수 없다.

## Evaluation(평가 관리) - 🛠️

- [ ]  평가를 추가할 수 있다.
- [ ]  특정 평가를 조회할 수 있다.
- [ ]  평가와 평가항목을 함께 생성할 수 있다.
- [ ]  평가항목 없이 평가를 생성할 수 있다.
- [ ]  모집 없이 평가를 생성할 수 없다.
- [ ]  모든 (상세한) 평가를 조회할 수 있다.
- [ ]  평가를 삭제할 수 있다.
- [ ]  이전 평가로 등록되어 있는 평가도 삭제 할 수 있다.

> 관리자가 실수하지 않는다는 가정하에 묻어두는 예외 상황들
> 
- 평가 항목 순서가 중복 가능함
- 평가 항목 순서에 1부터 시작하지 않아도 됨
- 평가 항목 이름도 중복이 가능함
- 이전 평가 중복도 가능함 → 평가 대상자 불러오기 시 치명적일 수 있음
- 평가 항목의 최대 점수가 0점도 가능함

## Mission(과제)(과제관리) - 🛠️

- [ ]  과제를 추가할 수 있다.
- [ ]  특정 모집의 모든 과제를 조회할 수 있다.
- [ ]  해당 평가에 이미 등록된 과제가 있는 경우 예외를 던진다.
- [ ]  과제를 삭제할 수 있다.
- [ ]  제출 가능한 상태의 과제를 삭제하면 예외가 발생한다.

## Mission(과제)(🙋🏻‍♂️)

**주의! 과제 조회를 위해서는 관리자의 평가자 불러오기가 선행되어야 한다(EvaluationTarget 항목의 가장 위 체크리스트를 확인해주세요)**

- [x]  특정 모집에 해당하는 나의 과제들을 조회할 수 있다.
- [x]  숨겨진 과제는 지원화면에 보여지지 않는다.

## Assignment(과제 제출물) - 🙋🏻‍♂️

- [x]  제출 가능한 과제에 과제 제출물을 제출할 수 있다.
- [x]  기간이 지난 과제에 과제 제출물을 제출할 수 없다.
- [x]  평가 대상자가 아닌 경우 과제를 제출할 수 없다
- [x]  이미 과제를 제출한 경우 새로 제출할 수 없다
- [x]  기간이 지나지 않은 과제에 대해 과제 제출물을 수정할 수 있다.
- [x]  기간이 지난 과제에 대해 과제 제출물을 수정할 수 없다.
- [x]  나의 과제 제출물을 조회할 수 있다.
- [x]  과제를 제출한 적이 있는 경우 과제 제출물 조회시 제출한 과제 제출물이 나온다.

## EvaluationTarget(평가 대상자) - 🛠️

- [ ]  불러오기 버튼으로 평가대상자를 업데이트 할 수 있다.
    - 부정 행위자로 등록된 평가 대상자는 불러오기시 불합격 상태가 된다.
    - 이전 평가에서 합격 상태인 평가 대상자들만 불러와진다.
    - 이전 평가가 없을 시 전체 평가 대상자를 불러온다.
- [ ]  탭을 클릭해서 해당 평가의 평가 대상자들을 조회할 수 있다.
- [ ]  평가지 다운로드 버튼으로 평가지를 다운로드 받을 수 있다
- [ ]  평가지를 업로드해 평가를 업데이트할 수 있다.
    - [ ]  FAIL, PASS, PENDING, WAITING 이외의 평가상태를 적는 경우 평가 결과가 업로드되지 않는다.
    - [ ]  평가 항목의 점수란에 숫자가 아니거나 최대 점수보다 높은 점수를 입력시 평가 결과가 업로드되지 않는다.
- [ ]  검색창을 통해 평가대상자를 검색할 수 있다
- [ ]  평가결과 다운로드로 평가결과 파일을 다운로드 받을 수 있다.
- [ ]  과제가 있는 평가일 경우 과제 제출물과 함께 평가하기 다이얼로그를 확인할 수 있다.
    - [ ]  평가대상자의 과제 제출물이 있을 경우 해당 과제 제출물을 함께 보여준다.
    - [ ]  평가대상자의 과제 제출물이 없을 경우 해당 과제 제출물이 빈 값으로 보여진다.
- [ ]  과제가 없는 평가일 경우 과제 제출물이 조회되지 않는다.
- [ ]  관리자가 평가페이지에서 평가불러오기를 했을 때, 지원자 상태가 "대기" 중이었다. 상태가 "대기중"인 지원자가 과제를 제출하고, 관리자가 평가페이지에서 평가 불러오기를 다시 하면 상태가 "합격"으로 변경되어 있다. ("대기중"인 경우 과제를 제출하기만 하면 "합격"상태가 된다.)

**전체 지원자 탭**

- [ ]  전체 지원자를 조회할 수 있다.
- [ ]  `평가 결과 다운로드` 버튼을 누르면 지원자 정보 excel을 다운로드할 수 있다.

**평가 탭**

> 관리자 사용시 전제 사항 or 절대 실수하지 말아야 할 점
> 
- 평가 완료된 이전 평가는 평가 대상자 불러오기를 누르지 않는다.
- 프리코스 내에서는 부정 행위자가 발생하지 않는다.
- 평가지 업로드 시 평가지의 컬럼명이나 지원자의 정보는 건드리지 않는다.

## Cheater(부정 행위자) - 🛠️

- [ ]  모든 부정행위자 이메일을 조회할 수 있다.
- [ ]  부정행위자 조회시 부정행위자의 정보가 파기된 경우 `(이름 없음)`으로 표기된다.
- [ ]  부정행위자를 추가할 수 있다.
- [ ]  이미 등록된 이메일의 부정행위자를 추가할 수 없다.
- [ ]  부정행위자를 삭제할 수 있다.
- [ ]  이름이나 이메일로 지원자를 검색해 부정행위자를 추가할 수 있다.

## API 요청 - 🙋🏻‍♂️

- [ ]  관리자 API를 요청시 예외가 발생한다.

## Mail(메일) - 메일관리 - 🛠️

- [x]  메일 발송 시 제목, 본문 없이 메일을 보낼 수 없다.
- [x]  보낸사람 항목에 메일 발신자 계정이 "EMAIL"(문자그대로) 이 아니어야 한다.
- [ ]  받는 사람이 한 명도 없을 경우, 수신 확인용 계정에만 발송한다.
- [ ]  메일 발송 시, 수신 확인용 계정이 메일을 받는다.
- [ ]  50명 이상을 대상으로 메일을 발송 시, 50명 단위로 잘라서 메일을 보낸다.
- [x]  메일 수신 시 숨김 참조로 수신하여 다른 수신자를 확인 할 수 없다.
- [x]  개별 불러오기 기능(이름 또는 이메일로 검색가능)으로 수신자를 불러 올 수 있다.
- [x]  그룹 불러오기 기능으로 모집, 평가, 평가 상태를 기반으로 수신자를 추가할 수 있어야 한다.
- [x]  수신자가 중복 될 경우 리스트에 추가되지 않는다.
- [x]  파일을 첨부해서 발송할 수 있다.
- [ ]  첨부된 파일을 X버튼을 눌러 삭제할 경우 해당 파일은 발송되지 않아야 한다.
- [x]  메일 발송 시, 메일 관리 화면에 메일 제목, 보낸 시간 받은 사람 수가 표시되어야 한다.
- [ ]  메일 발송 시, 본문에 html 태그를 넣을 경우 태그로 인식된다. (`<a href="~~"/>`)
- [x]  자세히 보기 버튼을 누를 경우 (첨부파일이 제외된)메일 발송 정보가 남아야 한다.

**Comment by Sehwan-Jang** [comment]
## Flow Chart
![image](https://user-images.githubusercontent.com/68985748/137089651-6f3b7e50-2fa5-4809-91e2-533a23a5eb4c.png)
+ 노란색 : 지원화면
+ 회색 : 관리화면

**Comment by MyaGya** [comment]
1팀: 마갸, 시드 ,도비
2팀: 아론, 파노, 포츈
