### ISSUE TITLE
Figma로 우테코 시계를 디자인해 본다. - 5월 2일

### ISSUE THREAD

**Issue by woowapark** [woowacourse/service-issues#98]
### 목적
프로젝트 온보딩  
: 지원 플랫폼 UI 개발(개선 및 신규 기능 추가) 을 진행할 때, 요구사항을 UI로 시각화해서 소통할 수 있다. 
- 1 Figma 사용에 익숙해진다.
- 2 서로에게 익숙해진다. 

### 진행 순서
- 최소한의 Figma 연습해보기: 카드 UI 디자인 (with 공원) - 4월 27일(수)
- 우테코 시계 요구사항을 Figma에서 시안으로 만들어보기 

### 온보딩 자료
- [지원 플랫폼 Figma](https://www.figma.com/file/1gceuyT9aDojgnnUXWwurO/?node-id=1105%3A3)

**Comment by greenblues1190** [comment]
# 소피아, 우디

@soyi47

<img width="863" alt="스크린샷 2022-04-30 오후 1 40 25" src="https://user-images.githubusercontent.com/44823900/166091314-5f850527-1172-488b-baa5-60e6f8f5d892.png">

<div align="center">
  <a href="https://www.figma.com/file/l4ohJlhpjfhRxBkzx7rXiZ/Untitled?node-id=0%3A1">
    figma
  </a>
</div>

## 목적

프로젝트 온보딩
: 지원 플랫폼 UI 개발(개선 및 신규 기능 추가)을 진행할 때, 요구사항을 UI로 시각화해서 소통할 수 있다.

- [x] Figma 사용에 익숙해진다.
- [x] 서로에게 익숙해진다.

## 소요 시간

5시간

## 느낀 점

### 설계의 중요성

- 피그마도 CDD 적용하기. 컴포넌트를 잘 설계해야 수정이 용이할 듯.
- 미리 컬러 팔레트를 설정해 놓고 골라쓰면 좋을 것 같다.
- 그리드를 잡고 시작하면 편하다. 안 잡아서 오래 걸림.

### 피그마 잘 활용하는 연습 필요

- 상태값을 이용해 UI 제어하는 법 찾아봐야할 듯.
- 어떻게 CSS스러운 방식으로 아이템을 정렬 할 수 있을까? flex 적용 방법이 궁금하다.

### 그 외

시디과 학생한테 배민 상품권을 주고 열정 페이를 시키는 건 어떨까? 아프니까 청춘이다...

### 참고한 자료

- https://www.uidesigntemplates.com/#popular

**Comment by hwangstar156** [comment]
# 비녀💪🏻 x 록바🦾 x 스밍 💪🏿

## 데모 영상 🎥
![ezgif com-gif-maker (9)](https://user-images.githubusercontent.com/85891751/166133390-d437d705-39de-46de-98c0-d933b882e8da.gif)

## [피그마 링크](https://www.figma.com/file/qEJ4aPoSoR57Rz074Pv4HP/clock?node-id=9%3A729)

## 목적
프로젝트 온보딩
: 지원 플랫폼 UI 개발(개선 및 신규 기능 추가)을 진행할 때, 요구사항을 UI로 시각화해서 소통할 수 있다.

- [x] Figma 사용에 익숙해진다.
- [x] 서로에게 익숙해진다.

## 소요시간
2시간 30분

## 느낀점

### 스밍😎
- 컴포넌트화를 안하고 프레임에만 이름을 주고 사용하여서 나중에 header 컴포넌트를 바꿀떄 불편함이 있었다. 컴포넌트의 중요성을 알게 되었다.
-  프로토타입을 통하여 동적(?)으로 움직일수 있도록 할수 있었다.

### 비녀😎
-  재사용만 생각하다보니 유지보수가 용이한 컴포넌트를 활용해야겠다는 생각을 못했다.
다음엔 수정의 자동화도 도전해보겠다.프로토타입 너무 섹시하다. 나,,, 디자이너 해야될지도,,,? 

### 록바😎

- 진행 방식은 컴포넌트를 구성하고 큰 페이지를 만들어가는 방식으로 진행했다. 처음으로 피그마를 사용하지만, 3인 페어를 진행해서 굉장히 수훨했다.

### 아쉬운점

- 점심에 먹은 라멘이 좀 별로였다..
