### ISSUE TITLE
코틀린으로 워들을 구현해 본다. - 5월 23일

### ISSUE THREAD

**Issue by woowahan-pjs** [woowacourse/service-issues#99]
저장소: https://github.com/woowahan-pjs/kotlin-wordle

### 페어

- 애쉬, 제로
- 로마, 파랑
- 케이, 차리
- 조조그린, 페퍼

**Comment by woowahan-pjs** [comment]
### 상호 코드 리뷰

- [x] 애쉬 -> 로마
- [x] 제로 -> 파랑
- [x] 로마 -> 케이
- [x] 파랑 -> 조조그린
- [x] 케이 -> 페퍼
- [x] 차리 -> 애쉬
- [x] 조조그린 -> 제로
- [x] 페퍼 -> 차리

**Comment by kth990303** [comment]
워들 마무리 확인되어 클로즈하겠습니다!
